### ISSUE TITLE
Check parameters are encoded by default going in

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAuthR#101]
Looks like it doesn't as per https://github.com/MarkEdmondson1234/googleAuthR/issues/100

**Comment by MarkEdmondson1234** [comment]
This unfortunately broke bigQueryR as it can't deal with NULL parameters.

**Comment by carlganz** [comment]
This broke my code as well. This works:
```{R}
paste(names(pars_args), 
             vapply(pars_args, URLencode, reserved = TRUE, character(1)), 
             sep='=', collapse='&')
```
vapply checks that each value returned is consistent with FUN.VALUE i.e. if FUN.VALUE is length n then it checks that each value returned is length n.

**Comment by MarkEdmondson1234** [comment]
Thanks @carlganz !  I'll put that in now so at least GitHub works

**Comment by MarkEdmondson1234** [comment]
I think this is done, but let me know if not.
