### ISSUE TITLE
Problem with gar_auth_service

### ISSUE THREAD

**Issue by riccardopinosio** [MarkEdmondson1234/googleAuthR#108]
Hello,

I'm trying to authenticate to my google cloud account using a json service token. What I do is
call googleAuthR::gar_auth_service('path_to_json_file'). What I get back is:

`
Error in init_oauth_service_account(self$secrets, scope = self$params$scope,  : 
  Bad Request (HTTP 400).
`

I'm pretty sure the json key is well-formed as I have regenerated prior to trying. Any ideas on what this error is?

Riccardo.

**Comment by MarkEdmondson1234** [comment]
Do you perhaps need to set the scopes?  You can use `options(googleAuthR.verbose = 2)` to examine the auth URL and see if anything is amiss.

**Comment by MarkEdmondson1234** [comment]
See if anything here helps you: http://code.markedmondson.me/googleAuthR/articles/troubleshooting.html

**Comment by riccardopinosio** [comment]
Hello!

Indeed, I needed the scopes! Thanks a million!

R.

**Comment by twizy83** [comment]
Hello @riccardopinosio How did you solve this problem.

I am currently running into it myself.

**Comment by MarkEdmondson1234** [comment]
@twizy83 have you looked through the troubleshooting page? http://code.markedmondson.me/googleAuthR/articles/troubleshooting.html

**Comment by riccardopinosio** [comment]
@twizy83 
I solved the problem by setting the scopes as detailed in Mark's link above.

**Comment by MarkEdmondson1234** [comment]
The API you are connecting to should list it’s required scopes, or you can use the RStudio addin that comes within googleAuthR to search for it. You should only need this if you are building an API yourself, not if you are using a dependent package as the package should set it for you. See the link for details.

**Comment by MarkEdmondson1234** [comment]
Ah ok, may be worth opening an issue for that as a lot of different concepts getting mixed up, which I don't blame you for as it is confusing first blush.

Short answer, this should work:

```r
library(googleCloudStorageR)
library(bigQueryR)

# should be "https://www.googleapis.com/auth/cloud-platform"
getOption("googleAuthR.scopes.selected")

googleAuthR::gar_auth_service("location_of_json_key.json", 
                       scope = "https://www.googleapis.com/auth/cloud-platform")

bqr_list_datasets("your-project")
gcs_list_buckets("your-project")
```

If that works, to get auto-authentication on package load I suggest setting your environment arguments like so:

`
BQ_AUTH_FILE="location of json file"
`

Long answer - scopes are set per package, and are put into the global option `"googleAuthR.scopes.selected"` - the package checks against this for authentication and API calls.  To auth with BigQuery and Google Cloud Storage which is a common need, there is a scope that covers both which is `"https://www.googleapis.com/auth/cloud-platform"` that BigQuery uses but Google Cloud Storage doesn't, so if you load `bigQueryR` first it will default to that, but if `googleCloudStorageR` is loaded first it will only be `"https://www.googleapis.com/auth/devstorage.full_control"` which won't allow BigQuery.

The scopes are not saved in the JSON files to authenticate with, they are project ranged so any scope activated for that project can be used with them.

**Comment by r-lister** [comment]
Hi Mark,

Thanks for your response, it was the scope issue.

Looking at the ?gar_auth_service help page, the default scope reverts to getOption("googleAuthR.scopes.selected") 
but mine is still NULL (as I'm guessing is the case for riccardo and twizy)

How does the googleAuthR.scopes.selected get populated?

Anyway adding the scope parameter to the googleAuthR::gar_auth_service function allowed me to finally authenticate, thanks for all you help :)

If anyone else comes across this issue, I found this list of scopes helpful too 
https://developers.google.com/identity/protocols/googlescopes
If in doubt "scope = https://www.googleapis.com/auth/cloud-platform" should do the job.

**Comment by MarkEdmondson1234** [comment]
Glad its sorted

> How does the googleAuthR.scopes.selected get populated?

On library load, it sets the option, or if you set it yourself using `googleAuthR::gar_set_client()`, or directly via `options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform"`

> If anyone else comes across this issue, I found this list of scopes helpful too
https://developers.google.com/identity/protocols/googlescopes

There is also an RStudio addin if you have loaded `googleAuthR` that lists them
