### ISSUE TITLE
Failing gar_batch_walk() Due to json lexical error - Spreadsheets v4

### ISSUE THREAD

**Issue by bradgwest** [MarkEdmondson1234/googleAuthR#110]
Hi Mark, thanks in advance for any time you spend on this.

## What's Wrong

I'm attempting to call a batch request for data in ca. 100 spreadsheets. The only path argument that is changing is the the spreadsheet key, other parameters remain identical. This seems like an appropriate use case for `gar_batch_walk`. I receive a 200 status code (using `options(googleAuthR.verbose) = 1`, however, the call throws the `jsonlite` error: `lexical error: invalid char in json text`. 

## Steps to reproduce the problem

Here's a minimal example to reproduce. When simply the function generated by `gar_api_generator`, I get the expected response. It fails, however, on the call to `gar_batch_walk` call.  Obviously my client secret, id, and spreadsheet key would be changed.

```
options(
  "googleAuthR.scopes.selected" = 
    c("https://www.googleapis.com/auth/spreadsheets.readonly", 
      "https://www.googleapis.com/auth/drive.readonly"),
  'googleAuthR.client_id' = "XXX",
  "googleAuthR.client_secret" = "XXX",
  "googleAuthR.batch_endpoint" = "https://www.googleapis.com/batch/spreadsheets/v4",
  "googleAuthR.verbose" = 1)

spreadsheet_key <- "XXX"

ga_paths <- list(spreadsheets = spreadsheet_key,
                 values = "Sheet1!A1:B1")
ga_pars <- list(majorDimension = "COLUMNS", 
                valueRenderOption = 'UNFORMATTED_VALUE',
                dateTimeRenderOption = 'SERIAL_NUMBER')

f <- googleAuthR::gar_api_generator(
  baseURI = "https://sheets.googleapis.com/v4/",
  http_header = 'GET',
  path_args = ga_paths,
  pars_args = ga_pars
)

# this throws an error
batch_res <- 
  googleAuthR::gar_batch_walk(f,
                              walk_vector = c(spreadsheet_key),
                              gar_pars = ga_pars,
                              gar_paths = ga_paths,
                              path_walk = 'spreadsheets',
                              data_frame_output = FALSE,
                              batch_size = 100)

# this works
res <- f()
```

## Expected output

I'd expect to see a list of length 10 as the response, with values in `response$content$values`

## Actual output

```
2018-02-20 15:06:09> Batch API limited to [100] calls at once.
2018-02-20 15:06:09> Token exists.
2018-02-20 15:06:09> Constructing batch request URL for: https://sheets.googleapis.com/v4/spreadsheets/XXX/values/Sheet1!A1:B1?majorDimension=COLUMNS&valueRenderOption=UNFORMATTED_VALUE&dateTimeRenderOption=SERIAL_NUMBER
2018-02-20 15:06:09> Making Batch API call
Error: lexical error: invalid char in json text.
                                       Not Found
                     (right here) ------^
```

## Session Info

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] googleAuthR_0.6.2.9000 httr_1.3.1             compiler_3.4.3        
 [4] R6_2.2.2               assertthat_0.2.0       tools_3.4.3           
 [7] curl_3.0               yaml_2.1.16            Rcpp_0.12.15          
[10] memoise_1.1.0          jsonlite_1.5           digest_0.6.15         
[13] httpuv_1.3.5           openssl_0.9.7  
```

**Comment by MarkEdmondson1234** [comment]
I'll try to reproduce the error, but first glance you shouldn't need to pass the `gar_pars`and `gar_paths` arguments since those are static and within the function `f` you have built already, that may help:

```r
# this throws an error
batch_res <- 
  googleAuthR::gar_batch_walk(f,
                              walk_vector = c(spreadsheet_key),
                              path_walk = 'spreadsheets',
                              data_frame_output = FALSE,
                              batch_size = 100)
```

**Comment by MarkEdmondson1234** [comment]
I'll try to reproduce and get back to you!

**Comment by MarkEdmondson1234** [comment]
Unfortunately, it looks like this API does not support the generic batching, at least I can't find the usual support article on batching in their documentation.  

This is the same as with the v4 Google analytics API, but like that it may be because there is a native batching method available - for GoogleSheets their version is  [here](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGet), but that doesn't look as useful since you can only batch values from one sheet at the time.

Its a similar situation again to the Google Analytics APIs - v3 supports batching over several accounts, whilst v4's native batching only lets you query the same account ID.  It means v3 is actually quicker for fetching from lots of accounts as you can fetch 10 at a time. 

After a quick look though it seems you wouldn't be able to do this with googlesheets v3 since its XML based.

The only other approach then would be to parallelise R's end, by perhaps launching lots of R processes to make your API requests using `future` or similar.

**Comment by bradgwest** [comment]
Mark, thanks for the quick feedback. I was initially worried that may be the case when I couldn't find documentation about the v4 googlesheets batch endpoint. I guess I got too excited about the possibility of batching and forgot to follow up on that lead. 

Cheers
