### ISSUE TITLE
authentication fails when call back uri is "localhost" and not "127.0.0.1"

### ISSUE THREAD

**Issue by brucebotes** [MarkEdmondson1234/googleAuthR#12]
The function gar_shiny_getUrl does not generate the correct uri when "localhost" is used instead of "127.0.0.1". This will happen when  the Google Web API's callback uri is created as "localhost". The port is escaped as http://localhost/1234 instead of http://localhost:1234. 

Check line 110 - 116 in "googleAuthR_shiny.R"

**Comment by MarkEdmondson1234** [comment]
Thanks for the report, I can easily fix this but first I will check to see if the Google API console accepts localhost as a callback.  I vaguely remember it does not, and you have to use 127.0.0.1 instead.

**Comment by MarkEdmondson1234** [comment]
Ok no localhost is fine in the console, so I'll do this fix for the next release on CRAN.

**Comment by MarkEdmondson1234** [comment]
This should now be fixed in the github version, on CRAN next release. Thanks for the report!

**Comment by brucebotes** [comment]
Hi Mark,

I understood it to be the other way around - no absolute IP addresses.....

Cheers
Bruce

**Comment by MarkEdmondson1234** [comment]
The previous 127.0.0.1 works, use it myself. But both should be supported now, give it a go by installing from github.
