### ISSUE TITLE
with_shiny does not function as expected with eventReactive({input$loginButton,....

### ISSUE THREAD

**Issue by benjaminrobinson** [MarkEdmondson1234/googleAuthR#122]
## What goes wrong
I want a `selectInput` I'm building on the server side of a shiny app that I'm using your FANTASTIC package to build to be able to be triggered using an eventReactive that's based on the login button that's being triggered using an `callModule(googleAuth, "loginButton")` call instead of the current `actionButton` that's used.  When I load my app I get an automatic error saying:  ```Need to provide the reactive access token in shiny_access_token argument. 
         e.g. shiny_access_token=access_token()```.  I want the `selectInput` to generate only when the user hits the `loginButton` to authenticate.  Its a small thing but I'm wondering if there's a way around that.

## Expected output
![image](https://user-images.githubusercontent.com/7928978/40339335-fcd88a02-5d47-11e8-87fb-6554d6c0459e.png)

## Actual output
![image](https://user-images.githubusercontent.com/7928978/40339236-80dc60f4-5d47-11e8-91ef-d839928ab9db.png)

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Just included a link to the "Auth Token URL"

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed
![image](https://user-images.githubusercontent.com/7928978/40339399-57d36cce-5d48-11e8-9f89-a4871e0106d8.png)

**Comment by MarkEdmondson1234** [comment]
Could I see some code you have tried?  I think I usually use `shiny::conditionalPanel()` for what you are asking but would like to make sure I'm talking about the same thing.

**Comment by MarkEdmondson1234** [comment]
Is this still an issue?

**Comment by benjaminrobinson** [comment]
I abandoned the project that used the panel so you can close the issue.  Thanks for being responsive!  That's the best that a user of open source software can expect!
