### ISSUE TITLE
sporadic authentication failure

### ISSUE THREAD

**Issue by bobcohensf** [MarkEdmondson1234/googleAuthR#124]
## What goes wrong
I have a multi-user shiny app running on shiny server pro that sporadically fails authentication with the errors below.  It gets into a state where you push the login button, authentication fails, and then from then on, authentication keeps failing each time you push the login button.  Browser restart seems to fix the problem.  Seems like a caching or cookie problem?  I specify a cache file with:

options(googleAuthR.httr_oauth_cache = authCacheFile)

but that file never seems to get touched.

Does this ring any bells for anyone?

## Actual output
  Warning in authReturnCode(session) :
    securityCode check failed in Authentication! Code:jyB21PFq1xAGOehIMXwh Expected:Yuj8OZWjkTzuaRTp2r4f
  Request failed [401]. Retrying in 1 seconds...
  Request failed [401]. Retrying in 1 seconds...
  2018-06-25 13:52:45> Request Status Code: 401
  No token found
  Warning: Error in : API returned: Invalid Credentials
  Stack trace (innermost first):
      75: checkGoogleAPIError
      74: doHttrRequest
      73: g
      72: f
      71: with_shiny
      70: <reactive:userDetails> [/gnet/resfiles3/resweb/web/dev/shiny/ptd/shinyapps/.switchr/                                         GermlineAlignmentTool/                   GermlineAlignmentTool/shiny/server.R#119]
      59: userDetails
      58: observerFunc [/gnet/resfiles3/resweb/web/dev/shiny/ptd/shinyapps/.switchr/GermlineAlignmentTool/GermlineAlignmentTool/       shiny/ server.R#131]
       1: runApp
  Warning in authReturnCode(session) :
    securityCode check failed in Authentication! Code:vQf2T4Tz1vgiFSfLRofD Expected:Yuj8OZWjkTzuaRTp2r4f
  Warning in authReturnCode(session) :
    securityCode check failed in Authentication! Code:vQf2T4Tz1vgiFSfLRofD Expected:Yuj8OZWjkTzuaRTp2r4f
  Warning in authReturnCode(session) :
    securityCode check failed in Authentication! Code:vQf2T4Tz1vgiFSfLRofD Expected:Yuj8OZWjkTzuaRTp2r4f
  Warning in mclapply(list("heavy", "light"), function(x) { :
    1 function calls resulted in an error
  Warning in authReturnCode(session) :
    securityCode check failed in Authentication! Code:vQf2T4Tz1vgiFSfLRofD Expected:Yuj8OZWjkTzuaRTp2r4f
Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed

**Comment by bobcohensf** [comment]
Actually, browser restart does not seem to solve the problem.

**Comment by MarkEdmondson1234** [comment]
the `options(googleAuthR.httr_oauth_cache = authCacheFile)` only affects the offline cache file, not the live Shiny token.

Its most likely that the URL is still using an old session `state` URL parameter.  By default the URL carries a random string per Shiny session, which on a browser refresh will not match the new Shiny session.

A could of different approaches to tackle it would be to:

a) have a log out button that links back to root domain (www.myapp.com) 
b) use the JS authentication instead (`gar_shiny_jsUI`)
c) set the state argument to a fixed value

There are some improvements that may be made in the future that are in some of the open issues here, that may be around for future versions of `googleAuthR`

**Comment by bobcohensf** [comment]
It's not the information in the URL - I use a bookmark to go back to the server without any of the authentication data in the url.  Push the button, it gets an error and the button rerenders with "Login via Google"

**Comment by MarkEdmondson1234** [comment]
Hmm well this line 

`securityCode check failed in Authentication! Code:jyB21PFq1xAGOehIMXwh Expected:Yuj8OZWjkTzuaRTp2r4f`

...indicates that another R shiny session has been started which doesn't match the token in the R environment.  The random strings are the ones that have been generated in each session.  Perhaps on Shiny server pro it keeps the R session running the background?

**Comment by MarkEdmondson1234** [comment]
Any progress with this or shall I close the issue?  Check out the demo apps in the inst folder if that helps.

**Comment by bobcohensf** [comment]
couldn't get it to work - went with another solution
