### ISSUE TITLE
autoGoogleAPI not generating all methods for sheet v4 API

### ISSUE THREAD

**Issue by alberthkcheng** [MarkEdmondson1234/googleAuthR#125]
It only generated function under "spreadsheets" section but not others, i.e. spreadsheets.values
https://developers.google.com/sheets/api/reference/rest/

The issue is that below function look for "methods" object in root level only but spreadsheets.values are under "resources" object and may be necessary to always enable recursive.
```
recursive_key_finder <- function(the_list, key = "methods"){
  
  if(key %in% names(the_list)){
    ## success - add to global
    set_global(c(get_global(), the_list[[key]]))
    ## but there could also be some within
  } else {
    ## recursive
    lapply(the_list, recursive_key_finder, key = key)
  }
  
  get_global()
}
```

**Comment by MarkEdmondson1234** [comment]
Thanks very much for this!  I will just test it against some other API libraries and merge if successful.
