### ISSUE TITLE
googleAuthR works great locally but can't seem to make it work on Shinyapps.io

### ISSUE THREAD

**Issue by FDragon88** [MarkEdmondson1234/googleAuthR#128]
## What goes wrong

`Warning: Error in : Not authenticated. Run scr_auth()
`

Using googleAuthR packages, i have no problem creating a shiny dashboard that connects to both Search console and Analytics APIs. The app uses the indicated credentials and renders the data. But in Shinyapps.io, and after analysing the logs, it seems it fails the Search Console authentification.

## Steps to reproduce the problem

**Global.R**

```
library(dplyr)
library(shiny)
library(shinydashboard)
library(shinycssloaders)
library(DT)
library(googleAnalyticsR)
library(searchConsoleR)

library(googleAuthR)
options(googleAuthR.scopes.selected=c('https://www.googleapis.com/auth/webmasters.readonly','https://www.googleapis.com/auth/analytics.readonly'))
options("googleAuthR.webapp.client_id"='MYID')
options("googleAuthR.webapp.client_secret"='MYPASSWORD')
options(httr_oauth_cache = FALSE)
options(googleAuthR.verbose = 2)
```

**Server.R**

```
server <- function(input, output, session) {

  
  token <- callModule(googleAuth, "login", approval_prompt = "force")
  

  ga_accounts <- reactive({

    validate(
      need(token(), "Authentication Required!")
    )
    googleAuthR::with_shiny(ga_account_list,
                   shiny_access_token = token())
    
  })
  
  selected_id <- callModule(authDropdown, "auth_menu", ga.table = ga_accounts)
  

  scdata <- eventReactive(input$goButton2, {
    debut <- input$auditrange[1]
    fin <- input$auditrange[2]
    url <- input$url
    
    validate(
      need(token(), "Authentication Required!")
    )
    
  
    googleAuthR::with_shiny(search_analytics, siteURL = url,
               startDate = debut, endDate = fin,
               dimensions = c("page","query"),
               rowLimit = 20000,
               shiny_access_token = token())
    
  })

...

}

```

**ui.R**

```

ui <- dashboardPage(
  
  dashboardHeader(title = "Blah"),
  dashboardSidebar(
    sidebarMenu()
    
  ),
  dashboardBody(
    
    tabItems(
      
      tabItem(tabName = "Blabla",
              fluidRow(
                box(
                  
                  googleAuthUI("login"),
                  authDropdownUI("auth_menu"),
                  dateRangeInput("auditrange", "Date range",
                                 start  = Sys.Date()-30,
                                 end    =  Sys.Date()-3,
                                 min    = "2001-01-01",
                                 max    = Sys.Date()-3),
                  textInput(inputId ="url", label="L'adresse du site (avec https, sans /)", value = "", width = NULL, placeholder = NULL),
                  
                         
                  
                  box(actionButton("goButton2", "Submit"))
                  
                  
                )
)))))
                
                

```
## Expected output

Locally, the data is parsed correctly, without any error messages.

## Actual output

On ShinyApps.io, everything works up until the search console authentification : 

`Warning: Error in : Not authenticated. Run scr_auth()
`
And then it stops.

## Session Info

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rsconnect_0.8.8        bindrcpp_0.2.2         googleAuthR_0.6.3      searchConsoleR_0.3.0   googleAnalyticsR_0.5.0
 [6] DT_0.4                 shinycssloaders_0.2.0  shinydashboard_0.7.0   dplyr_0.7.6            shiny_1.1.0           

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18      pillar_1.3.0      compiler_3.5.1    later_0.7.3       bindr_0.1.1       bitops_1.0-6     
 [7] tools_3.5.1       packrat_0.4.9-3   digest_0.6.15     jsonlite_1.5      memoise_1.1.0     tibble_1.4.2     
[13] pkgconfig_2.0.1   rlang_0.2.1       rstudioapi_0.7    crosstalk_1.0.0   curl_3.2          yaml_2.2.0       
[19] httr_1.3.1        sourcetools_0.1.7 htmlwidgets_1.2   tidyselect_0.2.4  glue_1.3.0        R6_2.2.2         
[25] RJSONIO_1.3-0     purrr_0.2.5       tidyr_0.8.1       magrittr_1.5      promises_1.0.1    htmltools_0.3.6  
[31] assertthat_0.2.0  mime_0.5          xtable_1.8-2      httpuv_1.4.5      RCurl_1.95-4.11   openssl_1.0.2    
[37] crayon_1.3.4

**Comment by MarkEdmondson1234** [comment]
I think this is related to https://github.com/MarkEdmondson1234/googleAuthR/issues/57

shinyapps.io doesn't seem to respect the options you set.

The solution is to use either the JavaScript version of auth instead, or to set your client.id/secret etc. via environmental arguments instead.

Let me know if that works for you, and feel free to reopen if its not the solution :)
