### ISSUE TITLE
Allow partitionID (namespaceID) in the API request to datastore

### ISSUE THREAD

**Issue by SeagleLiu** [MarkEdmondson1234/googleAuthR#132]
## What goes wrong
I am trying to enhance the "rdatastore" package, such that we can specify a namespace during lookup/query/commit. But I could not figure out where or how to pass in that argument. 

According to the Google API documentation, the namespaceID can be used as part of the partitionID (which default case is just projectID).
https://cloud.google.com/datastore/docs/reference/data/rest/v1/PartitionId

Based on the current implementation, the projectID was coded as part of the base_url, such as

```r
base_url <- paste0("https://datastore.googleapis.com/v1/projects/",
                     project)
    load_ds <- googleAuthR::gar_api_generator(
                              paste0(base_url, ":lookup"),
                              "POST",
                               data_parse_function = function(x) x)
```

The problem seems to become what is the "base_url" should be if we want to specify as namespace under that project. The namespace does not seem to belong to the "path" part of the key in datastore, which could be handled by the existing "path_arguments" in gar_api_generator
https://cloud.google.com/datastore/docs/reference/data/rest/v1/Key

Thank you so much.

**Comment by MarkEdmondson1234** [comment]
I'm a bit unsure what the problem is, can you give some examples of the URLs you are trying to generate?

I think you could do it like this:

```
base_url <- paste0("https://datastore.googleapis.com/v1/)
load_ds <- googleAuthR::gar_api_generator(
                              paste0(base_url, ":lookup"),
                              "POST",
                                path_arguments = list(projects = project),
                               data_parse_function = function(x) x)
load_ds()
```

But some example URLs will help

**Comment by MarkEdmondson1234** [comment]
Or skip using the dynamic path arguments and build it yourself like this:

```r
full_url <- sprintf("https://datastore.googleapis.com/v1/projects/%s:lookup", project)
load_ds <- googleAuthR::gar_api_generator(full_url,
                              "POST",
                               data_parse_function = function(x) x)
```

**Comment by SeagleLiu** [comment]
Sorry, the "lookup" part is an example. The problem is how to tell the server (or figure out the right form of url) that we need to get into a specific namespace instead of the default one.

I am not sure if this helps. I will later create an example project on this.

**Comment by SeagleLiu** [comment]
Thank you so much Mark. I figured this out. The partitionID is still part of the_body of this request. I need to add in an additional field in the list to be passed in. 

Here is the raw request form from the google api explorer:
 POST https://datastore.googleapis.com/v1/projects/gdxcrazyscience:lookup?key={YOUR_API_KEY}

{
 "keys": [
  {
   "partitionId": {
    "namespaceId": "ns1",
    "projectId": "gdxcrazyscience"
   },
   "path": [
    {
     "kind": "testkind2",
     "name": "tt2"
    }
   ]
  }
 ]
}

Correspondingly, the request in R can be made from 
rm(list = ls())
Sys.setenv("GCS_AUTH_FILE" =
             "/home/seagle/Documents/GCP/gdxcrazyscience-seagleserve2.json")
Sys.setenv("GCS_PROJECT" = "gdxcrazyscience/ns1")
library(rdatastore)
datastore_auth()
path_item <- list(partitionId =
                    list(projectId = "gdxcrazyscience",
                         namespaceId = "ns1"),
                  path = list(kind = "testkind2", name = "tt2"))

tLookup <- googleAuthR::gar_api_generator(
  "https://datastore.googleapis.com/v1/projects/gdxcrazyscience:lookup",
  "POST",
  data_parse_function = function(x) x)

tLookup(the_body = list(keys = path_item))

Sorry this is messy. I will clean up and contribute back to the rdatastore package.

Thanks a lot.

**Comment by MarkEdmondson1234** [comment]
Ok cool!  Glad it is sorted.
