### ISSUE TITLE
Errors display a lot of unhelpful text

### ISSUE THREAD

**Issue by hadley** [MarkEdmondson1234/googleAuthR#137]
```R
library(googleAnalyticsR)

ga_auth()
df <- google_analytics(1, date_range = c("2018-01-01", "yesterday"), metrics = "sessions")
#> Request failed [403]. Retrying in 1 seconds...
#> Request failed [403]. Retrying in 1.7 seconds...
#> 2019-01-06 08:49:33> Request Status Code: 403
#> Scopes: https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.readonly https://www#> .googleapis.com/auth/analytics.manage.users.readonly https://www.googleapis.com/auth/analytics.edit https://www#> .googleapis.com/auth/analytics.manage.users https://www.googleapis.com/auth/analytics.user.deletion
#> App key: 289759286325-da3fr5kq4nl4nkhmhs2uft776kdsggbo.apps.googleusercontent.com
#> Method: new_token
#> Error : API returned: User does not have sufficient permissions for this profile.
#> Error in error_check(out) : 
#>   API returned: User does not have sufficient permissions for this profile.
```

* You appear to be retrying a 403 request inappropriately. I assume you're automatically retrying HTTP requests to improve robustness, but I don't think you should do this for a 400 error statuses.

* There's a lot of additional information that obscures the actual error: I'm not sure why the time or the scopes are useful here. If you think they are important, I'd recommend not displaying them, but instead caching, and giving the user an explicit function to call for additional info.

* The actual error message `User does not have sufficient permissions for this profile.` is repeated twice

* You should use `call. = FALSE` to avoid printing `error_check(out)`; this doesn't give any additional info here.

In my opinion, an ideal error here would look more like:

```R
df <- google_analytics(1, date_range = c("2018-01-01", "yesterday"), metrics = "sessions")
#> Error: API [403]: User does not have sufficient permissions for this profile.
```

**Comment by MarkEdmondson1234** [comment]
Oh when I moved the issue I lost my comment. Ack well.  But will look at toning down the message spam at `googleAuthR`level.

**Comment by MarkEdmondson1234** [comment]
* You appear to be retrying a 403 request inappropriately. I assume you're automatically retrying HTTP requests to improve robustness, but I don't think you should do this for a 400 error statuses.

This was already possible via the `googleAuthR.HttrRetryTerminateOn` option to pass to `httr::RETRY()` but NULL so I set the default to 403.

**Comment by hadley** [comment]
These changes a big improvement, but I'm still seeing duplication:

```R
2019-01-08 07:59:40> Request Status Code: 403
Error : API returned: User does not have sufficient permissions for this profile.
Error in error_check(out) : 
  API returned: User does not have sufficient permissions for this profile.
```

**Comment by MarkEdmondson1234** [comment]
Ah the last error is in googleAnalyticsR so that is removed in the GitHub version of it.

**Comment by hadley** [comment]
Ok, that's better:

```R
2019-01-08 08:10:14> Request Status Code: 403
Error : API returned: User does not have sufficient permissions for this profile.
2019-01-08 08:10:14> Downloaded [1] rows from a total of [].
```

It's a bit weird to have output after an error though,  and surely I didn't actually succeed in downloading one row?

(Also note that you have a space before the ":" in the error)

**Comment by MarkEdmondson1234** [comment]
I added all the 4XX errors for now, as I need to keep retries in for 5XX which often just need a back off.

> `2019-01-08 08:10:14> Downloaded [1] rows from a total of []`.
> It's a bit weird to have output after an error though, and surely I didn't actually succeed in downloading one row?

Yes...will take a look at that back at `googleAnalyticsR`

(Can't see where to change the error space ?! Its just a normal error `stop("API returned: ", paste(ga.json$error$message), call. = FALSE)`)

**Comment by MarkEdmondson1234** [comment]
Seems if you wrap an error with `try()` it adds the space:

```r
try(stop("an error", call. = FALSE))
Error : an error
> stop("an error")
Error: an error
```

**Comment by MarkEdmondson1234** [comment]
Removing the `googleAnalyticsR` error call made it populate the data.frame, it now correctly stops and uses `tryCatch()` as I know how to use that these days.

```r
library(googleAnalyticsR)
ga_auth()
Token cache file: /Users/IIH-Nordic/dev/auth/analytics.httr-oauth
df <- google_analytics(1, date_range = c("2018-01-01", "yesterday"), metrics = "sessions")
2019-01-08 15:54:05> Request Status Code: 403
Error: API returned: User does not have sufficient permissions for this profile. 
```

**Comment by hadley** [comment]
Looks great!
