### ISSUE TITLE
When app is deployed: Error: invalid_request  Missing required parameter: client_id

### ISSUE THREAD

**Issue by ArbenKqiku** [MarkEdmondson1234/googleAuthR#139]
## What goes wrong

Locally the app works fine, I am able to login to all my google accounts and make it work. When I deploy the app, and I when I try to log in I get the following error:

Error: invalid_request
Missing required parameter: client_id

## Steps to reproduce the problem
Please note that if a reproduceable example that I can run is not available, then the likelihood of getting any bug fixed is low. 

library(shiny)
library(googleAuthR)
library(googlesheets)

sheet_function_example = function(sheetname){
  #gs_auth(new_user = TRUE)
  current.sheet = gs_title(x = sheetname)
  gs_edit_cells(current.sheet, ws = "Feuille 1", input = Sys.time(), anchor = 'A1')
}

options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/drive")

#you may also set the client id and secret here as well
options(googleAuthR.client_id = "XXX",
        googleAuthR.client_secret = "XXX")

fileSearch <- function(query) {
  
  googleAuthR::gar_api_generator("https://www.googleapis.com/drive/v3/files/",
                                 "GET",
                                 pars_args=list(q=query),
                                 data_parse_function = function(x) x$files)()
}

## ui.R
ui <- fluidPage(     
  titlePanel("Reactivity"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      textInput(inputId = "caption",
                label = "1) Create a copy of the following template: https://goo.gl/UeQ5en
                2) Save it to your Google Drive
                3) Rename your sheet
                4) Insert the name of the sheet in the box below",
                value = "Insert Your Sheet Name"),
      submitButton("Confirm Sheet Name")),
    
    #Main panel for displaying outputs ----
    mainPanel(
      
      #Output: Formatted text for caption ----
      h3(textOutput("text", container = span))
    )
    )
  
  
  )

## server.R
server <- function(input, output, session){
  
  #create a non-reactive access_token as we should never get past this if not authenticated
  
  output$gdrive <- renderTable({
    req(input$query)
    
    #no need for with_shiny()
    fileSearch(input$query)
    
  })
  
  output$caption <- renderText({
    input$caption
  })
  
  output$text = renderText({
    counter = 0
    
    while(!input$caption == "Insert Your Sheet Name"){
      sheet_function_example(input$caption)
      counter = counter + 1
      if(counter > 0){
        break
      }
    }
  })
}

shinyApp(gar_shiny_ui(ui, login_ui = gar_shiny_login_ui), server)

## Expected output

I would expect that I am able to login, insert the name of the sheet that I want to modify and run the app. However, after I login, I get the aforementioned error.

## Actual output
Error: invalid_request
Missing required parameter: client_id

## options(googleAuthR.verbose=2)
I get no output when I run this: options(googleAuthR.verbose=2)

## Session Info

Here are the versions of the packages:
googlesheets_0.3.0 
googleAuthR_0.7.0  
shiny_1.2.0

Thank you for your help man. I really appreciate it :)

**Comment by MarkEdmondson1234** [comment]
The clientID and clientSecret needs to be either set before the library loads:

```r
#you may also set the client id and secret here as well
options(googleAuthR.client_id = "XXX",
googleAuthR.client_secret = "XXX")
library(googleAuthR=
```

Or, better, use the `gar_set_client()` function and point the `web_json` (web_json as this is an online Shiny app) at the client credentials you download from your GCP.  (Note, not the authentication JSON file, but the client credentials.)

e.g.

```r
library(googleAuthR)
gar_set_client(web_json = "location_of_creds.json")
```
