### ISSUE TITLE
Shiny client_id/client_secret option parsing incorrect?

### ISSUE THREAD

**Issue by rwutzke** [MarkEdmondson1234/googleAuthR#14]
I noticed that when using Shiny you'll need to set options:
googleAuthR.webapp.client_id
googleAuthR.webapp.client_secret
instead of:
googleAuthR.client_id
googleAuthR.client_secret
Is that behaviour desirable?
The "problem" might be in the lines:
https://github.com/MarkEdmondson1234/googleAuthR/blob/master/R/googleAuthR_shiny.R#L64-L65
Doesn't googleAuthR usually use those options without webapp and googleAnalyticsR uses them including the webapp? It might be easier to use the same naming in both packages or set options for googleAuthR automatically when specifc options for googleAnalyticsR are set?

Anyhow https://github.com/MarkEdmondson1234/googleAnalyticsR_public#example-adding-your-own-google-developer-console-keys should probably be updated for correct behaviour (ie also set "webapp" options for googleAuthR or only set those ones and do not set the non "webapp" options?

**Comment by MarkEdmondson1234** [comment]
Hi - they are actually different keys, although perhaps the documentation should be clearer.

`googleAuthR.webapp.client_id, googleAuthR.webapp.client_secret` are used for the online Oauth2 system, e.g. Shiny apps

`googleAuthR.client_id, googleAuthR.client_secret` are used when you authenticate offline, e.g. `ga_auth(new_user=TRUE)`

**Comment by rwutzke** [comment]
Right on, that makes absolutely sense. But is there a use case where you want to have different webapp keys for googleAuthR and googleAnalyticsR? It might make sense to still automatically check whether those keys are set for googleAnalyticsR and only use your default project keys in case there is nothing else defined?

Just out of interest, is there a reason / use case where you want online and offline keys to be different? Otherwise it might be convenient to set the other automatically if either (webapp or non webapp) is set?

**Comment by MarkEdmondson1234** [comment]
If you don't put any web keys, then it will default to `googleAuthR`'s default ones.  You are fine to use those to test the library, but it just means that if lots of other people are doing it as well it may hit the API limit per day.  This isn't likely at the moment.

The online and offline keys are supplied differently by Google API console, you get them from two different menus.  If they can be interchanged that would, I agree, a lot easier to deal with, but I think it won't work.  I will test this though. 

e.g. from here: https://console.developers.google.com/apis/credentials/oauthclient , you have two options - "webapp" and "other", that I've used to date.
