### ISSUE TITLE
Refresh token using Shiny

### ISSUE THREAD

**Issue by rwutzke** [MarkEdmondson1234/googleAuthR#15]
Hey, using the library I noticed that a while after authenticating, a consecutive GA query will result in an invalid credentials error. Inspecting the issue I found that the object holding the token (auth_token) got an attribute `credentials` that contains `access_token`, `token_type`, `expires_in` and `refresh_token`. Right after authentication the value of `expires_in` is `3599` which makes me believe that the unit of this value is seconds, which would mean it expires after one hour. Also, `refresh_token` is `NULL`. 
Is there a way to refresh the token? This also occurs when during that 60min some queries are being made.

I would be very grateful for any ideas or hints :)

PS: The same happens when using shinyga.

**Comment by MarkEdmondson1234** [comment]
First of all thanks loads for all the feedback, it will make it faster stronger better for all in the future. 

Yes, there is a one hour timeout for online Shiny apps, which is standard I think from the Google tokens. For most of my apps that's been more than adequate, I generally download everything I need on first login and segment in R afterwards. Rather than constant calls to the api over the hour. 

It is possible to get a refresh token and use that to request a new auth token after the hour. I'll also look to see if the time can be increased optionally.

**Comment by rwutzke** [comment]
I am happy to be of help! Once I am a bit more familiar with the library, I'd be glad to make contributions as well. Also I'd like to thank you for your quick and informative replies.

What would I need to do to get a refresh token? It would be perfect to be able to refresh it without further user interaction (eg periodically every 40min or so) while the Shiny user session is still running.

**Comment by MarkEdmondson1234** [comment]
I checked here at the [Google web OAuth2 page](https://developers.google.com/identity/protocols/OAuth2WebServer) and it looks like you can't change the timeout.

Depending on your needs, you could keep track of the tokens time left (its an hour by default) and then prompt the user to reauthenticate.

However if you want no user interaction, you need to set `access_type=offline` (a recent addition in `gar_shiny_getAuthUrl()` that I will expose externally soon) and then use the refresh token in any future calls to get a new access token.  

If you are using this library without Shiny, this is what `httr` does - you will notice it saying `Refreshing OAuth2 Access` when you are using it beyond the first hour.

**Comment by MarkEdmondson1234** [comment]
Also bear in mind that a user logging in the second time will be quick, as it doesn't need to go through the OAuth2 permission screen again due to Google saving a cookie with their details, so its a click but not a big hurdle.

**Comment by MarkEdmondson1234** [comment]
A bit more on this, as its related to another project I'm on.

```r

shinyServer(function(input, output, session) {
## This is a normal access token that times out after one hour
  access_token  <- reactiveAccessToken(session)
  
  ## Setting access_type to "offline" means you can get a refresh token
  output$loginButton <- renderLogin(session, access_token(),
                                    logout_class = "",
                                    access_type = "offline",
                                    revoke = TRUE)
  
  ## Its polite to include this to stop you 
  ## having access to a user's account without their knowledge
  revokeEventObserver(access_token(), input)
  
  ## to use a refresh token you need to write the refresh and token to a file
  observeEvent(input$writeAuthToken, {
    shiny::validate(
      need(access_token(), "Authenticate")
    )
    
    ## only there the first time you give access
    message("Writing auth tokens to file")

    dput(isolate(access_token()$credentials$access_token), "./access_token.gar")
    
    if(!file.exists("./refresh_token.gar")){
      dput(isolate(access_token()$credentials$refresh_token), "./refresh_token.gar")       
    }
   
  })
  
  ## this is like access_token() but can be refreshed offline
  ## will put this into a function in the package eventually
  access_token_read <- eventReactive(input$readAuthToken, {
    token <- dget("./access_token.gar")
    refresh_token <- dget("./refresh_token.gar")
    message("Read token")
 
    ## ripped from googleAuthR::gar_shiny_getToken
    client.id     <- getOption("googleAuthR.webapp.client_id")
    client.secret <- getOption("googleAuthR.webapp.client_secret")
    
    gar_app <- httr::oauth_app("google", key = client.id, secret = client.secret)
    
    scope_list <- getOption("googleAuthR.scope")
  
    token_formatted <-
      httr::Token2.0$new(app = gar_app,
                         endpoint = httr::oauth_endpoints("google"),
                         credentials = list(access_token = token,
                                            token_type = "Bearer",
                                            expires_in = 3598,
                                            refresh_token = refresh_token),
                         params = list(scope = scope_list, type = NULL,
                                       use_oob = FALSE, as_header = TRUE),
                         cache_path = getOption("googleAuthR.httr_oauth_cache"))
    
    token_formatted

  })

  ## demo using the normal token that runs out of time
  website_df <- reactive({
    validate(
      need(access_token(), "Authenticate")
    )

    with_shiny(your google api function, access_token())           
  })

  ## demo using the refresh token
  website_df2 <- reactive({
    validate(
      need(access_token_read(), "Authenticate")
    )

    with_shiny(your google api function, access_token_read())           

    
  })
}
  ```

**Comment by rwutzke** [comment]
First of all, thanks for all those answers! Prompting the user again is something that I would love to evade (even considering the fact that it would be 2 clicks at most).

But concerning your last comment, I haven't had the possibility to try it out yet, but I've got a quick question: why do I need to store the refresh token (as well as the token) in a file?

**Comment by MarkEdmondson1234** [comment]
No props :)

When using refresh it should be just the first time they login you can capture the refresh token.
The example code above is for a project where I store the refresh token in a database, for offline refreshes of customer data - you wouldn't need to write to a file for one session.

**Comment by MarkEdmondson1234** [comment]
I'm marking this closed now as its possible using the example I gave above.
