### ISSUE TITLE
ShinyAuthR stops authdropdown from populating on a seperate tab

### ISSUE THREAD

**Issue by Jackwcalladine** [MarkEdmondson1234/googleAuthR#154]
## What goes wrong
i have a shiny application that uses googleAuthR to connect to the google analytics V4 API, this works perfectly and presents me with drop-downs that i can use to pull down data from various accounts/webID/views. However i have implemented a shinyauthr login screen, this utilizes a JavaScript login and logout button. i can log in, which renders my whole application, and i can click log in to authorize my google analytics, but the dropdowns no longer populate themselves with the accounts i have access to. the dropdown will work if it is on the same page as the google authorization, but if it is on another tab it does not work

## Steps to reproduce the problem

**here is some greatly reduced code, this will make a shiny application with just a login, google authorization and table dropdown, but encapsulates the issue.**

```
library(googleAnalyticsR)
library(googleAuthR)
library(shiny)
library(shinyjs)
library(shinydashboard)
library(shinyauthr)

#login database
user_base <- tibble(
    user = c("user1"),
    password = sapply(c("pass1"), sodium::password_store), 
    permissions = c("admin"),
    name = c("User One")
)


ui <- dashboardPage(
    
    # put the shinyauthr logout ui module in here
    dashboardHeader(
        title = "Test Report",
        tags$li(class = "dropdown", style = "padding: 8px;", logoutUI1("logout"))
    ),
    
    # setup a sidebar menu to be rendered server-side
    dashboardSidebar(
        collapsed = TRUE, sidebarMenuOutput("sidebar")
    ),
    
    
    dashboardBody(
        shinyjs::useShinyjs(),
        
        # put the shinyauthr login ui module here
        loginUI1("login"),
        
        # setup any tab pages you want after login here with uiOutputs
        tabItems(
            tabItem("GA", uiOutput("GA")),
            tabItem("data", uiOutput("data"))
    )
))

server <- function(input, output, session) {
    
    # login status and info will be managed by shinyauthr module and stores here
    credentials <- callModule(login1, "login", 
                              data = user_base,
                              user_col = user,
                              pwd_col = password,
                              sodium_hashed = TRUE,
                              log_out = reactive(logout_init()))
    
    # logout status managed by shinyauthr module and stored here
    logout_init <- callModule(logout1, "logout", reactive(credentials()$user_auth))
    
    # this opens or closes the sidebar on login/logout
    observe({
        if(credentials()$user_auth) {
            shinyjs::removeClass(selector = "body", class = "sidebar-collapse")
        } else {
            shinyjs::addClass(selector = "body", class = "sidebar-collapse")
        }
    })
    
    # only when credentials()$user_auth is TRUE, render your desired sidebar menu
    output$sidebar <- renderMenu({
        req(credentials()$user_auth)
        sidebarMenu(id="sbmenu",
                    menuItem("Google analytics", tabName = "GA", icon=icon("lock-open")),
                    menuItem("data", tabName = "data"))
                   
    })
    

    output$GA <- renderUI({
        req(credentials()$user_auth)
        tagList(
            h2("Authorize your Google Analytics Account"),
                fluidRow(
                    box(title="Authentication",solidHeader = T,status="primary",width=12,height="150px",googleAuth_jsUI("auth"))
                )
            )
    })
    
    output$data <- renderUI({
        req(credentials()$user_auth)
        tagList(
            h2("Authorize your Google Analytics Account"),
            fluidRow(
                box(width=12,height="100px",column(width = 12, authDropdownUI("auth_dropdown",
                                                                              inColumns = TRUE)))
            ))
    })
    
    #get auth token
    auth <- callModule(googleAuth_js, "auth")
    #get ga accounts
    ga_accounts <- reactive({
        req(auth())
        
        with_shiny(
            ga_account_list,
            shiny_access_token = auth()
        )
        
    })
    #get view id for dashboard graph
    view_id <- callModule(authDropdown, "auth_dropdown",
                          ga.table = ga_accounts)
    
}
# Run the application 
shinyApp(ui = ui, server = server)

```

## Expected output
i expect a populated dropdown 

## Actual output
not a populated dropdown

what i receive from console:

2019-08-08 14:23:35> Request: https://www.googleapis.com/analytics/v3/management/accountSummaries/
2019-08-08 14:23:35> No paging required

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed
- Session info -----------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 ctype    English_United Kingdom.1252 
 tz       Europe/London               
 date     2019-08-08                  

- Packages ---------------------------------------------------------------------------------------------------------------------------------------------------
 package          * version  date       lib source        

 googleAnalyticsR * 0.6.0    2018-12-21 [1] CRAN (R 3.6.1)
 googleAuthR      * 0.8.0    2019-06-30 [1] CRAN (R 3.6.0)
 sessioninfo        1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
 shiny            * 1.3.2    2019-04-22 [1] CRAN (R 3.6.0)
 shinydashboard   * 0.7.1    2018-10-17 [1] CRAN (R 3.6.0)
 shinyjs          * 1.0      2018-01-08 [1] CRAN (R 3.6.1)

i am using the functions from shinyauthR but not the actual package. the vignettes contain these functions.

**Comment by MarkEdmondson1234** [comment]
Try setting `suspectWhenHidden=FALSE` in the output of the token and/or table e.g. https://stackoverflow.com/questions/41622795/shiny-only-calculating-when-the-user-is-looking-at-the-output

**Comment by Jackwcalladine** [comment]
Great, that worked, thank you Mark!
