### ISSUE TITLE
Use of isFALSE in R < 3.5

### ISSUE THREAD

**Issue by matthijsvanderloos** [MarkEdmondson1234/googleAuthR#158]
## What goes wrong
While using the package in R <3.5 the following error is raised:

```R
Error in isFALSE(.auth$auth_active) : could not find function "isFALSE"
```
Apparently a function in the package uses `base::isFALSE()` but this has only been introduced in R 3.5. The requirements for googleAuthR are R >= 3.3.0, however.

**Comment by MarkEdmondson1234** [comment]
Thanks, I will raise the requirements

**Comment by MarkEdmondson1234** [comment]
Hmm actually thats a pretty big step for just one function, instead I'll put it in as a utility like `gargle` does

```r
isFALSE <- function(x) identical(x, FALSE)
```

So it should still be ok on R 3.3.0 after this commit.
