### ISSUE TITLE
Copying token to different remote server no longer works

### ISSUE THREAD

**Issue by explodecomputer** [MarkEdmondson1234/googleAuthR#159]
## What goes wrong

I use googleAuthR in this package for basic authentication https://github.com/mrcieu/TwoSampleMR. Often the package needs to be used on a server with no interactive browser and in HPC environments. When googleAuthR was in version < 1.0.0 the procedure was:

1. On a local computer with a browser, create a .httr.oauth file
2. Copy that file to the server

And it would provide the token for authentication without need for a browser.

Since 1.0.0 I can no longer do this - after the file is copied to the server and I call it with `gar_auth` it still requires authentication in a browser.

## Steps to reproduce the problem

```
devtools::install_github("MRCIEU/TwoSampleMR")
devtools::install_github("MarkEdmondson1234/googleAuthR@v0.8.1")

library(TwoSampleMR) # this sets the scopes, client id etc
# Alternatively just set the options as defined here: https://github.com/MRCIEU/TwoSampleMR/blob/master/R/zzz.R#L34

gar_auth("file.oauth")
```

This will require authentication in the browser etc to generate `file.oauth`. Now copy `file.oauth` to server, follow the same steps as above and it generates the token without requesting authentication.

By contrast, if I do this in the latest version of googleAuthR, when trying to use the file to generate a token on the remove server I get:

```
> options(googleAuthR.verbose=2)
> a <- gar_auth("mrbase.oauth", email=TRUE)
2019-09-11 23:12:51> Reading token from file path
2019-09-11 23:12:51> Read token successfully from file
2019-09-11 23:12:51> Setting client.id from options(googleAuthR.client_id)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Error: GDK_BACKEND does not match available displays
```

Or if I try with use_oob

```
> a <- gar_auth("mrbase.oauth", email=TRUE, use_oob=TRUE)
2019-09-11 23:13:22> Reading token from file path
2019-09-11 23:13:22> Read token successfully from file
Enter authorization code: Error: GDK_BACKEND does not match available displays
```

What can I do to enable authentication on the server? 

## Session Info

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux release 6.4 (Carbon)

Matrix products: default
BLAS: /cm/shared/languages/R-3.5.1-ATLAS/lib64/R/lib/libR.so
LAPACK: /cm/shared/languages/R-3.5.1-ATLAS/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] googleAuthR_1.1.1  TwoSampleMR_0.4.22

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       later_0.7.4      digest_0.6.17    assertthat_0.2.0
 [5] R6_2.4.0         jsonlite_1.6     magrittr_1.5     httr_1.4.1
 [9] rlang_0.3.1      curl_3.2         promises_1.0.1   fs_1.3.1
[13] tools_3.5.1      glue_1.3.0       httpuv_1.4.5     compiler_3.5.1
[17] gargle_0.3.1     memoise_1.1.0    openssl_1.0.2
```

**Comment by MarkEdmondson1234** [comment]
This should still work, can you try it by specifying email=NULL? Also have you upgraded R from 3.5 recently?


________________________________

**Comment by explodecomputer** [comment]
Thanks for the quick reply

I just tried with R 3.6.0 and googleAuthR 1.1.1 but still no luck unfortunately

```
> a <- gar_auth("mrbase.oauth", email=TRUE)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
sh: /usr/bin/xdg-open: No such file or directory
^C

> a <- gar_auth("mrbase.oauth", email=NULL)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
sh: /usr/bin/xdg-open: No such file or directory
^C

> a <- gar_auth("mrbase.oauth")
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
sh: /usr/bin/xdg-open: No such file or directory
^C
```

**Comment by MarkEdmondson1234** [comment]
Ah ok, the token argument will support old tokens created but won't make new ones anymore, since the token is stored at a user level not project.   The website is updated with recommended workflows for server auth now: https://code.markedmondson.me/googleAuthR/articles/google-authentication-types.html#authentication-with-a-json-file-via-service-accounts which in turn points to this gargle article: https://gargle.r-lib.org/articles/non-interactive-auth.html

My recommendation is to use the service account token e.g. [`googleAuthR::gar_service_auth()`](https://code.markedmondson.me/googleAuthR/reference/gar_auth_service.html) instead.

**Comment by MarkEdmondson1234** [comment]
To your specific issue, I think the token you have stored is using a different client.id/scopes than the one on your server?

```
> a <- gar_auth("mrbase.oauth", email=TRUE)
2019-09-11 23:12:51> Reading token from file path
2019-09-11 23:12:51> Read token successfully from file
2019-09-11 23:12:51> Setting client.id from options(googleAuthR.client_id)
```

This indicates you are reading the token, but then setting the client.id which would confuse things.  Do try with `googleAuthR>1.1.1` too, it may be a bug in the order of clientID being set. Its important the read token has the same client.id /scopes as the ones in the R session.

**Comment by explodecomputer** [comment]
Thanks for your patient help Mark.
I have looked at the use of the json file with a few users and I think it might not be feasible. I'm going to put some time aside to work on it more earnestly but for the time being I've put in a catch to direct users to install the pre 1.0.0 version of googleAuthR when the more recent one is detected. 
I might find myself asking more questions at some point, thanks again for your time!

**Comment by MarkEdmondson1234** [comment]
How about the second option above where you create your own cache folder instead? That should be the same as old behavirou.

  Can I also get more an idea of what your use case is, what API scopes are you authenticating under etc.?  Are you calling an API specifically?  I don't think your use case is out of the newest versions, just that your implementation before 1.0.0 was not catered for and got unsupported as a result, but backward compatibility is the main aim at the moment so I want to make sure it works with you.

**Comment by MarkEdmondson1234** [comment]
Specifically:

```r
make_auth_token <- function(email, cache_dir = ".secrets"){
  # designate project-specific cache
  options(gargle_oauth_cache = cache_dir)

  # check the value of the option, if you like
  gargle::gargle_oauth_cache()

  # trigger auth on purpose --> store a token in the specified cache
  token <- gar_auth(email=email)

  # see your token file in the cache, if you like
  list.files(".secrets/")

  token

}
```

**Comment by MarkEdmondson1234** [comment]
@explodecomputer did the above work at all?

**Comment by explodecomputer** [comment]
@MarkEdmondson1234 sorry for not responding sooner I do appreciate your help. Just trying to engineer a window of time to dedicate to this, but wasn't as quickly forthcoming as I imagined. Hopefully will be able to look into it in the next few days

**Comment by explodecomputer** [comment]
Hi @MarkEdmondson1234 

I am going with your advice on simply asking users to copy the directory with the token to the server. I had been trying this in development mode for the R package and it was giving me errors as I showed to you earlier, but after installing the package and running it there were no more errors. Not sure what is happening here but it's working just fine now. Thanks for all your help.
