### ISSUE TITLE
Validating Google Apps Domain - E-mail Extension

### ISSUE THREAD

**Issue by mshmei** [MarkEdmondson1234/googleAuthR#16]
Hey Mark and folks. I was able to set a basic ShinyApp with google Oauth2 using your library pretty effectively. The current script I have mirrors your example and I was wondering how I could validate the e-mail domain using the library e.g. I want to reject the token request unless the user has the account with "xxxx@thisdomainexactly.com".

**Comment by mshmei** [comment]
Did some more research and I think the particular parameter I'm looking for is this "hd" parameter.

https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

I don't believe this parameter can currently be set with googleAuthR.

**Comment by MarkEdmondson1234** [comment]
Hi @mshmei this looks like a useful addition.
What you have found about the hd parameter is very much like the existing `state` parameter so can be handled in a similar manner.  The `state` is just a random string generated at the time of the packge is loaded that is checked agaisnt to make sure its the same app recieving the auth tokens.  

The `state` and so `hd` will be parameters in the return authentication URL, not a JSON object (I think)

Where it validates the `state` is in this bit of code in `googleAuthR_shiny.R`:

```r
#' Returns the authentication parameter "code" in redirected URLs
#' 
#' Checks the URL of the Shiny app to get the state and code URL parameters.
#' 
#' @param session A shiny session object
#' @param securityCode A random string to check the auth comes form the same origin.
#' 
#' @return The Google auth token in the code URL parameter.
#' @family shiny auth functions
#' @keywords internal
authReturnCode <- function(session, 
                           securityCode=getOption("googleAuthR.securitycode")){
  
  pars <- shiny::parseQueryString(session$clientData$url_search)
  
  if(!is.null(pars$state)){
    if(pars$state != securityCode){
      warning("securityCode check failed in Authentication! Code:", 
              pars$state, 
              " Expected:", 
              securityCode)
      return(NULL)
    } 
  }
  
  if(!is.null(pars$code)){
    return(pars$code)
  } else {
    NULL
  }
}
```

A very similar treatment would add the hd feature (although make sure its optional)

If you would like to do it, just fork this repositary, make the change and commit to your fork, then submit a pull request and I can merge it in.
I'm planning a new release to CRAN next week so it would be great to have this there in that release.
Mark

**Comment by mshmei** [comment]
Hey Mark, after reading up a bit more on the "hd" param and how it works with Google OAuth 2.0; from what I understand, this is actually intended to be used with OpenIDConnect which is an additional layer on OAuth 2.0. I believe there is going to be an additional step with validating JWT (Json Web Tokens) which from the looks of, the lib cannot be easily reconfigured to deserialize this. Let me know if I'm simply incorrect so I can check out the code in more detail.

**Comment by MarkEdmondson1234** [comment]
Ah, I see - I don't know much about OpenID so perhaps not, but worth a go to try.

If it doesn't, I was going to suggest that you have some kind of whitelist that lists a user's email when they login (available in say the Google+ API) and check if they are  permitted to see your content.

**Comment by mshmei** [comment]
That may be a good approach. Hmmmm, are you suggesting the use of this Google+ API because right now the response token from Google with OAuth 2.0 doesn't let us handle things like e-mail domain extensions in R? Can you perhaps direct me to some reading in how to use Google+ API? I haven't found anything regarding this yet.

**Comment by MarkEdmondson1234** [comment]
Its a bit patchy, I think some APIs return the user email, but some don't.  

Google+ one does though for sure. https://developers.google.com/+/web/api/rest/latest/people#resource - I also see domain in there.

**Comment by mshmei** [comment]
Hey Mark, thanks for the direction on this. I was able to successfully use the Google+ API and add a way of handling the e-mail domain extension. 

FYI, the gar_api_generator() can do this - 

```
## global.R
get_email <- function(){
  
  f <- gar_api_generator("https://www.googleapis.com/plus/v1/people/me", "GET")
  
  f()
 
}

```
I think we can close this issue now. I would like to look into how one can use OpenID in the future as a way of handling the e-mail domain extension as this would offload the authentication process to Google as currently, you'd have to handle the authentication with e-mail domain extension as a separate process.

**Comment by MarkEdmondson1234** [comment]
Great.  I have on my ToDo to make a googleAuthenticateR library using this library, seems this is a good use case.  Will keep in mind the OpenID stuff :)  Good luck with your app.
