### ISSUE TITLE
Can no longer authenticate with client ID / secret using httr::oauth2.0_token, can in version 0.7.0

### ISSUE THREAD

**Issue by cunningjames** [MarkEdmondson1234/googleAuthR#160]
## What goes wrong

I'm attempting to authenticate in order to use Google Cloud Storage. I have a credentials file with the client ID and client secret, but no visibility on API keys. With version 0.7.0 I was able to use `httr::oauth2.0_token` to create a a token file and then call `gar_auth` with that token file for browserless authentication, but this no longer works -- now I'm taken to a browser window (which fails in my environment) or googleAuthR hangs.

If this is expected behavior in this version of googleAuthR, I'd greatly appreciate a pointer on how I could make this work.

## Steps to reproduce the problem

Here's the code that still works to authenticate with googleAuthR 0.7.0, but no longer works:

    json_token <- jsonlite::read_json(path_to_credential_file.json)

    o2token <- httr::oauth2.0_token(
      endpoint = httr::oauth_endpoint(
        authorize = "https://accounts.google.com/o/oauth2/auth",
        access = "https://www.googleapis.com/oauth2/v4/token"
      ),
      app = httr::oauth_app(
        appname = "rstudio",
        key = json_token$client_id,
        secret = json_token$client_secret
      ),
      scope = json_token$scopes,
      client_credentials = TRUE,
      credentials = list(
        "refresh_token" = json_token$refresh_token,
        "token_type" = "Bearer"
      )
    )

    auth_file <- tempfile()

    saveRDS(list("123456" = o2token), file = auth_file)

    suppressMessages(googleAuthR::gar_auth(token = auth_file))

## Expected output

No output; usage of the Google Cloud Storage API would succeed.

## Actual output

Console hangs while I'm redirected to a browser window, which fails in my environment.

## Session Info

R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAuthR_1.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       crayon_1.3.4     digest_0.6.20    later_0.8.0     
 [5] assertthat_0.2.1 R6_2.4.0         jsonlite_1.6     magrittr_1.5    
 [9] httr_1.4.1       rlang_0.4.0      curl_4.0         rstudioapi_0.10 
[13] promises_1.0.1   fs_1.3.1         tools_3.6.1      glue_1.3.1      
[17] httpuv_1.5.1     yaml_2.2.0       compiler_3.6.1   gargle_0.3.1    
[21] memoise_1.1.0

**Comment by MarkEdmondson1234** [comment]
This was never how auth was supported to work before v0.7 so I'm surprised it did, it seems you have been doing more code than necessary, as you were replicating what functions did underneath (e.g. constructing the token etc.).  

For your use case I suggest using simple `gar_auth_service("your-json-cred-file.json")` which will work in all versions - see help here https://code.markedmondson.me/googleAuthR/reference/gar_auth_service.html

**Comment by MarkEdmondson1234** [comment]
And if its only google cloud storage in particular you are working with, then `googleCloudStorageR` has wrapped `gar_auth_service()`  in other convenience functions that you can read about here http://code.markedmondson.me/googleCloudStorageR/articles/googleCloudStorageR.html

**Comment by cunningjames** [comment]
Thanks a lot for your help -- I appreciate the response! Unfortunately, what I have access to isn't the service account auth file and doesn't include the private key. 

    > foo <- gar_auth_service("/oauth/auth.json")
    Error in gar_auth_service("/oauth/auth.json") : 
      $private_key not found in JSON - have you downloaded the correct JSON file? 
             (Service Account Keys, not service account client)

Neither I nor my colleagues have the administrative permissions necessary to download the service account file, so if I can figure out a way to authenticate with the resources we have that would be helpful (i.e. as in earlier versions of this library, or with Google's own libraries on the Python side). I'd be really grateful for any tips / guidance here.

**Comment by cunningjames** [comment]
Aha, I think I figured it out. It seemed to require a more complete specification of the endpoint (authorize / access / validate / revoke); then I could pass the httr token directly to `gar_auth()`. Sorry for troubling you.

**Comment by MarkEdmondson1234** [comment]
Working now then?  Yes you can pass a token through `gar_auth()` which loads it into the R environment, checks scopes etc.
