### ISSUE TITLE
Logout Button doesn't work on shinyapps.io ?

### ISSUE THREAD

**Issue by rwutzke** [MarkEdmondson1234/googleAuthR#17]
I just realized, that the Logout button doesn't work as expected when used @shinyapps.io . When I run the code locally everything works fine, but when I push the same project to the shinyapps platform, the logout button somewhere gets stuck.
It seems to me that the redirection to the base URL (without the query part ?state=xyz&code=xyz) doesn't work. The URL is set correctly in the link of the button (to the base URL) but it still "redirects" to the same page, ie with the query part. The token gets revoked in the process, so it's invalid, but still since the query parameters are set (with now invalid data) the button still shows 'Logout' and the function reactiveAccessToken(session) generates an (invalid) access token.

Any idea why this happens? The only difference between those two scenarios is as far as I can see the domain (localhost vs shinyapps), the protocol (http vs https), the subfolder the app is in ('/' vs '/appname'), and possibly the 'shiny engine' (the shinyapps server might use a different version?). But I don't see how any of this should affect the behaviour of the button?

In the network traffic I can see that even if the link of the button is set to the base URL, the URL including query string is being queried. Also I just realized that once the Logout Button is clicked the href attribute of the link changes from the base URL to the URL including the query string (with the state and code variable).

Would appreciate any help or hints :)

**Comment by MarkEdmondson1234** [comment]
Ahh, you are probably running into shinyapps.io's iframe they have around all apps, that has caused no ends of issues :) I will take a look at this.

**Comment by rwutzke** [comment]
Ah, right on, thanks!

**Comment by MarkEdmondson1234** [comment]
Shinyapps.io now doesn't use an iframe, but this still doesn't work so I'll look at what URL its using for the button

**Comment by MarkEdmondson1234** [comment]
So due to the funny way shinyapps.io treats this links this is still not ideal, but a workaround is to use JavaScript to redirect a user when they click on a button, that is easy to add if using https://github.com/daattali/shinyjs

Example code:

in server.R

```
observeEvent(input$reset_button, {
    
    shinyjs::runjs("window.location.href = 'https://yoursubdomain.shinyapps.io/yourapp';")
    
})
```

in ui.R
```
actionButton("reset_button", "Restart", icon = icon("undo"), class = "btn-info"))
```
