### ISSUE TITLE
googleSignIn documentation incorrect

### ISSUE THREAD

**Issue by jonthegeek** [MarkEdmondson1234/googleAuthR#171]
## What goes wrong

The googleSignIn documentation says the values are g_id, g_email, g_image, and signed_in, but the actual values are id, name, email, image, and signed_in. It looks like the fields are renamed from their in-module names during the return:

```> googleAuthR::googleSignIn
function (input, output, session) 
{
    check_package_loaded("shiny")
    shiny::reactive({
        shiny::req(input$g_id)
        list(id = input$g_id, name = input$g_name, email = input$g_email, 
            image = input$g_image, signed_in = input$signed_in)
    })
}
```

I assume the preferred fix would be to change the documentation (since anybody using this has to be grabbing the g-less version of the list element), but wanted to check before submitting a PR.

**Comment by MarkEdmondson1234** [comment]
Yes documentation fix preferred, thanks for spotting it! IIRC it was a relic of the code example it was built from.


________________________________
