### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by analyse9823** [MarkEdmondson1234/googleAuthR#173]
Can't verify me credentials as getting an error that 'Sign in with Google temporarily disabled for this app'

Screenshot → https://i.imgur.com/5wfwwxk.png

Code:
`library(googleAuthR)
> gar_auth()`

**Comment by MarkEdmondson1234** [comment]
Which client ID is this for? It needs to go through the verify app procedure with Google that you can follow in the Google client id setup screen in the GCP console. 

On Chrome you may also see a link that will let you pass the screen (advanced use)

**Comment by analyse9823** [comment]
The issue is from default Google App in the package.
To use features properly I've created new API ClientId and then pass to authorization.
