### ISSUE TITLE
Timeout was reached: [oauth2.googleapis.com] Resolving timed out after 10000 milliseconds

### ISSUE THREAD

**Issue by Antriksh-Jain-mpf** [MarkEdmondson1234/googleAuthR#181]
## What goes wrong
error was: Timeout was reached: [oauth2.googleapis.com] Resolving timed out after 10000 milliseconds
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [oauth2.googleapis.com] Resolving timed out after 10000 milliseconds

## Steps to reproduce the problem
I am using below code for making connection with GCP.

```
gcs_auth_file = "service accout json key path"
Sys.setenv("GCS_AUTH_FILE" = gcs_auth_file)
library(googleCloudStorageR)
gcs_auth(gcs_auth_file)
Sys.setenv("GCS_DEFAULT_BUCKET" = bucket_name)
googleAuthR::gar_auth_service(Sys.getenv('GCS_AUTH_FILE'), scope = getOption("googleAuthR.scopes.selected"))
googleCloudStorageR::gcs_global_bucket(Sys.getenv('GCS_DEFAULT_BUCKET'))
```

## Expected output
It should be able to authenticate successfully.

## Actual output
error was: Timeout was reached: [oauth2.googleapis.com] Resolving timed out after 10000 milliseconds
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [oauth2.googleapis.com] Resolving timed out after 10000 milliseconds

**Comment by MarkEdmondson1234** [comment]
The code used does not look optimal, it should be sufficient to use:

```r
Sys.setenv("GCS_DEFAULT_BUCKET" = bucket_name)
gcs_auth_file = "service accout json key path"
library(googleCloudStorageR)
gcs_auth(gcs_auth_file)
```

e..g don't confuse things by using `googleAuthR` too, that may overwrite required settings.

Are you behind a proxy?  It may be a more fundamental issue on not being able to connect to the Google API

**Comment by Antriksh-Jain-mpf** [comment]
Thank you for the response. I will change it accordingly. 
Regarding the timeout issue- It looks like Google API is taking more 10000 milliseconds to respond. Can you please let me know How can I increase the timeout parameter?                 Thanks.

**Comment by MarkEdmondson1234** [comment]
What is your internet speed? I think the timeout is at Googles end so don’t know if it can be changed.

**Comment by Antriksh-Jain-mpf** [comment]
Thank you for the response. I am able to find the issue. The issue was with the network firewall.Now, it works fine.Hence, closing the ticket.
