### ISSUE TITLE
Has the client JSON changed format?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAuthR#202]
Getting some reports that the client JSON you download no longer has "installed" field which would break new deployments.  Would really suck.

The files should all start with `{"installed":{...`

**Comment by aldomann** [comment]
I've noticed that as well. Actually, Web Clients start with `{"web":{...`, which makes the `googleCloudRunner::cr_setup_auth()` process impossible, since `validate_json()` expects `validated$installed$client_id` to exist.

**Comment by MarkEdmondson1234** [comment]
That should be ok, if you use web_json instead in `gar_set_client()`
