### ISSUE TITLE
First Time User Queries

### ISSUE THREAD

**Issue by debsush** [MarkEdmondson1234/googleAuthR#21]
Hi, 

I am using your package for the first time.  I have a shiny app and I am looking to build a google sign-in feature for my users.  Was wondering if your package can in anyway, aid my objective

Appreciate your guidance.

Regards,
SD

**Comment by MarkEdmondson1234** [comment]
Hi, yes that's pretty much it's purpose. Check out the examples in the readme here and let me know how it goes. :)
