### ISSUE TITLE
Error in Cloud Vision API response

### ISSUE THREAD

**Issue by ashgreat** [MarkEdmondson1234/googleAuthR#32]
When an image doesn't have any faces or landmarks, I get the following error message
`Error in `[.data.frame`(ga.json[[1]], 1) : undefined columns selected`
I get labels and image properties without any issues. Although I didn't try it, the problem may show up for logo and text as neither is present in the image.

I used the following image
![705806796981724110_1392487_bergdorfs](https://cloud.githubusercontent.com/assets/6580738/14616308/18875546-05aa-11e6-95be-3687f1a4edaf.jpg)

**Comment by MarkEdmondson1234** [comment]
Interesting application!  So to be clear, it works some of the time, but in certain responses you see the error?  Are you parsing the response at all?  And could you also point to where the error is called from? (full stack trace?)

**Comment by ashgreat** [comment]
Here is the code I used. It's simply the code that you have already shared. I used Google's API documentation to change the type of feature to landmark detection. I had the same problem when I use Face Detection. When I actually have faces in the picture, face detection worked fine.

The error pops up right after I execute the last line.

`
## Landmark Detection

body= paste0('{  "requests": [    {   "image": { "content": "',txt,'" }, "features": [  { "type": "LANDMARK_DETECTION", "maxResults": 20} ],  }    ],}')

## generate function call
simpleCall <- gar_api_generator(baseURI = "https://vision.googleapis.com/v1/images:annotate", http_header="POST" )

## set the request!
pp <- simpleCall(the_body = body)`

**Comment by ashgreat** [comment]
I just realized that I am commenting to you while I used the code from another developer. I am sorry for the mixup. The original blog post was here: http://flovv.github.io/Brand-Logos/

**Comment by MarkEdmondson1234** [comment]
Thanks for the link!  Great to hear about it. I will take a look through.

**Comment by ashgreat** [comment]
Thanks for the great package!

**Comment by MarkEdmondson1234** [comment]
This is solved over on RoogleVision

**Comment by ashgreat** [comment]
Thanks Mark. It's working now. I get no error after updated your package to the latest developer version
