### ISSUE TITLE
shiny connection not using set options

### ISSUE THREAD

**Issue by dealeyj** [MarkEdmondson1234/googleAuthR#33]
When running a shiny app, it looks like it reverts to a default client_id and client_secret.

Set up my own id and secret, and run the UrlShortener example provided by Mark.
```
options("googleAnalyticsR.webapp.client_id" = "10004359XXXXXXXXXXXXX")
options("googleAnalyticsR.webapp.client_secret" = "XLrPgyXXXXXXXXXXXXX")
runApp("UrlShortener",launch.browser=T,port=6443)

```

> Listening on http://127.0.0.1:6443
>Auth Token URL: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=201908948134-cjjs89cffh3k429vi7943ftpk3jg36ed.apps.googleusercontent.com&redirect_uri=http%3A%2F%2F127.0.0.1%3A6443&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Furlshortener&state=KXUoYt6jAqE9w2ZRXyh8&access_type=online&approval_prompt=auto

In the response_type, it looks like it is using a client_id that begins 2019089XXXXX, rather than the one I just set up (10004359XXXXXX). When I try to connect on this port, I get an error, but if I use the port in the example at vignette("googleAuthR") then it allows me to connect no problem (Port 1221).

Versions:
R 3.2.2
googleAnalyticsR 0.0.9001
googleAuthR 0.2.0

**Comment by MarkEdmondson1234** [comment]
May I ask for the code in the "UrlShortner" folder?  I suspect the option is getting overwritten when it launches, and you need to put the `options()` in a global of the Shiny app.

**Comment by dealeyj** [comment]
Hi Mark, please find below

# Saved in a separate file
options("googleAuthR.client_id" = "1000435987678-t1umhuo04ldnkpckuto6ukbk92mrfj2n.apps.googleusercontent.com")
options("googleAuthR.client_secret" = "XLrPgyjYY8BZSl3zyyyB6zUi")
options("googleAuthR.scopes.selected" = c("https://www.googleapis.com/auth/analytics", 
                                          "https://www.googleapis.com/auth/analytics.readonly", 
                                          "https://www.googleapis.com/auth/webmasters",
                                          "https://www.googleapis.com/auth/urlshortener"))
options("googleAnalyticsR.webapp.client_id" = "1000435987678-t1umhuo04ldnkpckuto6ukbk92mrfj2n.apps.googleusercontent.com")
options("googleAnalyticsR.webapp.client_secret" = "XLrPgyjYY8BZSl3zyyyB6zUi")



# For server
shorten_url <- function(url){
   body = list(
    longUrl = url
  )
  f <- gar_api_generator("https://www.googleapis.com/urlshortener/v1/url",
                         "POST",
                         data_parse_function = function(x) x$id)
  f(the_body = body)
}
shinyServer(function(input, output, session){ 
  ## Get auth code from return URL
  access_token  <- reactiveAccessToken(session)
  ## Make a loginButton to display using loginOutput
  output$loginButton <- renderLogin(session, access_token=access_token())
  api_output <- eventReactive(input$submit, {
    ## with_shiny() wraps your your_api_function to provide the arguments
    ## requires you to pass "shiny_access_token"
    short_url <- with_shiny(f = shorten_url, 
                            shiny_access_token = access_token(),
                            url=input$url)
  })
  output$short_url <- renderText({
    api_output()
  })
})




# For UI
shinyUI(
  fluidPage(
    loginOutput("loginButton"),
    textInput("url", "Enter URL"),
    actionButton("submit", "Shorten URL"),
    textOutput("short_url")
  ))

# Code to run the app
runApp("FirstBuild",launch.browser=T,port=1221)

**Comment by MarkEdmondson1234** [comment]
Hi, I have it working locally but improved the documentation a bit to explain where the various options, files etc. should go.  The below should work with your setup and your options:

#### Shiny authentication example

```r
## in global.R
library(googleAuthR)
library(shiny)

options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/urlshortener")
options(googleAnalyticsR.webapp.client_id = "YOUR_PROJECT_KEY")
options(googleAnalyticsR.webapp.client_secret = "YOUR_CLIENT_SECRET")

shorten_url <- function(url){
  
  body = list(
    longUrl = url
  )
  
  f <- gar_api_generator("https://www.googleapis.com/urlshortener/v1/url",
                         "POST",
                         data_parse_function = function(x) x$id)
  
  f(the_body = body)
  
}

## server.R
source("global.R")

server <- function(input, output, session){
  
  ## Create access token and render login button
  access_token <- callModule(googleAuth, "loginButton")
  
  short_url_output <- eventReactive(input$submit, {
    ## wrap existing function with_shiny
    ## pass the reactive token in shiny_access_token
    ## pass other named arguments
    with_shiny(f = shorten_url, 
               shiny_access_token = access_token(),
               url=input$url)
    
  })
  
  output$short_url <- renderText({
    
    short_url_output()
    
  })
}

## ui.R
ui <- fluidPage(
  googleAuthUI("loginButton"),
  textInput("url", "Enter URL"),
  actionButton("submit", "Shorten URL"),
  textOutput("short_url")
)


### If the above global.R, server.R and ui.R files are in folder "test" like so:
## /home
##    |->/test/
##            /global.R
##            /ui.R
##            /server.R
##
## Port 1221 has been set in your Google Project options as the port to listen to
## as explained in authentication setup section
## run below in /home directory
shiny::runApp("./test/", launch.browser=T, port=1221)

```

**Comment by dealeyj** [comment]
Just to note, I had to add the following code to Global.R as well

`options(googleAuthR.webapp.client_id = "YOUR_PROJECT_KEY")
options(googleAuthR.webapp.client_secret = "YOUR_CLIENT_SECRET")`
