### ISSUE TITLE
getUser Profile when logging in

### ISSUE THREAD

**Issue by debsush** [MarkEdmondson1234/googleAuthR#35]
Hi,

I was able to make the google login work in my webapp over shinyapps.io  Now the only think I would need is to be able to extract the authenticating users display name/ or user name at the end of the authentication proces without having to click any additional button and then display that name in my webapp like "Welcome John Doe".  I think I can manage the display once I am able to retrieve the username.  The challenge I am facing is as follows:
1. Which API should I call to get the display name (is there some code I can use as an example)
2. How do I execute this API call automatically once the authentication is successful using the token received

Thank you
SD

**Comment by MarkEdmondson1234** [comment]
Hello, this is a common enough request I put a tiny package together that uses the G+ API which will do as you ask. Check it out here:

https://github.com/MarkEdmondson1234/googleID





On Tue, May 24, 2016 at 3:05 AM -0700, "debsush" <notifications@github.com> wrote:












Hi,



I was able to make the google login work in my webapp over shinyapps.io  Now the only think I would need is to be able to extract the authenticating users display name/ or user name at the end of the authentication proces without having to click any additional button and then display that name in my webapp like "Welcome John Doe".  I think I can manage the display once I am able to retrieve the username.  The challenge I am facing is as follows:

1. Which API should I call to get the display name (is there some code I can use as an example)

2. How do I execute this API call automatically once the authentication is successful using the token received



Thank you

SD

**Comment by debsush** [comment]
Hi Mark,

Thank you so much for this new package which I was not aware of.  I am running into slight bit of an issue.  I want the script to first run the authentication and then automatically run the get_user_info script.  I used the below code under server.R which is only authorizing the user but is not storing the username post authentication into the variable UserName.  Please let me know the error on my part

```
  shinyjs::onclick("GoogLoginBtn",GoogLog())
  
  GoogLog<-function(){
  googleAuthR::gar_auth()
  user <- with_shiny(get_user_info)$name$givenName
  UserName<<-user
  }
```

**Comment by MarkEdmondson1234** [comment]
The `access_token()` method is needed for shiny apps.  

The example for shiny wasn't good, so I updated the readme with the below which should make things clearer:

```r
library(shiny)
library(googleAuthR)
library(googleID)
options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/userinfo.email",
                                        "https://www.googleapis.com/auth/userinfo.profile"))


ui <- shinyUI(fluidPage(

  googleAuthUI("example1"),
  p("Logged in as: ", textOutput("user_name"))

))


server <- shinyServer(function(input, output, session) {

  access_token <- callModule(googleAuth, "example1")

  ## to use in a shiny app:
  user_details <- reactive({
    validate(
      need(access_token(), "Authenticate")
    )

    with_shiny(get_user_info, shiny_access_token = access_token())

  })

  output$user_name <- renderText({
    validate(
      need(user_details(), "getting user details")
    )

    user_details()$displayName

  })


})

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by MarkEdmondson1234** [comment]
You will need to add the G+ API scopes to your project settings and the scopes.selected to have the data available in your app.

When a user logs out you could redirect to the same shiny app but in a non-logged in state (e.g. no code= or state= in the URL), which I only know can be done using the `shinyjs` library that I see you are already using.  I assume you are hiding logged in content via the check for the `access_token()` to be non-NULL.

**Comment by debsush** [comment]
This is great.  I will try it out in a few hours and then close the issue.  Thank you very much for your prompt response.  I wish I could upvote you.  I would definitely like to add you and your package in my webapp contributors list once it goes live

**Comment by debsush** [comment]
This worked like a charm.  Thank you and much appreciate.

**Comment by MarkEdmondson1234** [comment]
Great! Good luck with your app, send me a link when done and I can link to it in the readme here.

**Comment by debsush** [comment]
Sure.  Will do.  Thank you
