### ISSUE TITLE
On failed authentication, don't create the .httr-oauth file

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAuthR#4]
googleAuthR::gar_auth() ## fail auth by pushing "Cancel"
    googleAuthR::gar_auth() ## no new authentication flow started, but should be.

**Comment by jdeboer** [comment]
Hi @MarkEdmondson1234 , from the description of this issue, I am wondering if this might something that needs to be addressed within the httr package?

**Comment by MarkEdmondson1234** [comment]
I knew I had seen this somewhere before, and you have reminded me: yes it must be related to https://github.com/hadley/httr/issues/250

**Comment by MarkEdmondson1234** [comment]
There is actually a function to catch this but I may not have implemented it correctly: `is_legit_token()` in https://github.com/MarkEdmondson1234/googleAuthR/blob/master/R/googleAuthR_auth.R taken from Jenny's original code in googlesheets

**Comment by MarkEdmondson1234** [comment]
Fixed in httr 1.1.0 https://github.com/hadley/httr/commit/21f6d577462c3855e6c645fc699cec20a003bd85
