### ISSUE TITLE
parseBatchResponse() doesn't handle empty content responses

### ISSUE THREAD

**Issue by jarodmeng** [MarkEdmondson1234/googleAuthR#43]
`parseBatchResponse()` looks for `Content-Length:` to identify the response body. However, some API calls (e.g., [`delete`](https://cloud.google.com/storage/docs/json_api/v1/objects/delete) in Cloud Storage) return an empty body with no `Content-Length:` header. In parsing responses from such calls, `parseBatchResponse()` would fail because `index <- which(grepl("Content-Length:", x))` would set `index` to a zero-length vector. 

In such responses, the status header looks like `HTTP/1.1 204 No Content`. So perhaps `parseBatchResponse()` can test using the status header whether the response is empty or not before attempting to parse it as JSON.

**Comment by MarkEdmondson1234** [comment]
Thanks, good catch - I hadn't tested with batch DELETEs

**Comment by MarkEdmondson1234** [comment]
I added the check like you suggested, but not tested it yet
