### ISSUE TITLE
Batch calls for Google Vision API

### ISSUE THREAD

**Issue by snakonechny** [MarkEdmondson1234/googleAuthR#48]
Hello,

Thank you for this wonderful package! I'm running into some speed issues with Google Vision (individual calls for images take too long to complete and iterate through) and would like to send 100-500 calls at once. Could you provide a simple example for implementing this?

I currently have a function `imageProcessor` that takes in a vector of folders, iterates through all files in individual folders, and generates .txt documents per folder.

Thanks!

**Comment by MarkEdmondson1234** [comment]
Thanks for trying it out!

Simplest would be for you to generate your functions then pass them all to the `gar_batch()` function:

```
## make your functions
gvision1 <- function() {

  l <- gar_api_generator(...)
  l()
}
## from goo.gl API
gvision2 <- function(){

  f <- gar_api_generator(...)

  f()
}

ggg <- gar_batch(list(gvision1(), gvision2()))
### ggg is then a list of your responses
```

Perhaps you can make the functions in a `lapply()` call. You may want to make some kind of wrapper function that 

You will need to check with the API docs what the per-second limit is to see how many you can batch at a time.
