### ISSUE TITLE
Value of input$login in shiny server

### ISSUE THREAD

**Issue by Liuy12** [MarkEdmondson1234/googleAuthR#5]
Hi, Mark

Thanks for this very elegant package!

Seems that `loginOutput('login')` function does not have a value when accessed via `input$login` which is different from the behavior of `actionbutton('login1')` in shiny, such that when the an actionbutton is clicked the value of `input$login1` would be 1 otherwise 0. 

I'd like to make a dynamic UI in shiny based on the value of `input$login`, do you have any suggestions?

**Comment by MarkEdmondson1234** [comment]
Hi @Liuy12 glad you like it!

If you checkout `renderLogin`I called the actionLink `"signed_in"` - try looking for that for your dynamic UI.  I should probably document this!

renderLogin and loginOutput are really just wrappers to make it more convinient, if you take a look at them, but they use some internal functions that you could perhaps use:

```
renderLogin <- function(session, 
                        access_token, 
                        login_text="Login via Google",
                        logout_text="Logout",
                        login_class="btn btn-primary",
                        logout_class="btn btn-default"){
  shiny::renderUI({
    if(is.null(shiny::isolate(access_token))) {
      shiny::actionLink("signed_in",
                 shiny::a(login_text, 
                          href = gar_shiny_getAuthUrl(gar_shiny_getUrl(session)), 
                   class=login_class, 
                   role="button"))
    } else {
      shiny::a(logout_text, 
        href = gar_shiny_getUrl(session), 
        class=logout_class, 
        role="button")
    }
  })
}
```
Let me know if this helps?

**Comment by Liuy12** [comment]
@MarkEdmondson1234 

Hi, Mark, 

Thanks for your prompt response! Turns out that I have installed an older version. After install the latest version on github, I am able to access the value of `input$signed_in`. However, seems like that the value of `input$signed_in` stays the same ( as 0) even if I clicked the login button. 

I found a workaround by using the value of `shiny::isolate(access_token())` for my dynamic UI.

**Comment by MarkEdmondson1234** [comment]
Yes I updated after you raised the issue :)

Glad you found a solution, the problem is I realise is that when you click the login link, you actually reload the Shiny app so it resets to 0 again.  Are you just looking for a way to detect if a user is logged in?  In that case yes, I use `!is.null(access_token())` to detect that myself.

**Comment by Liuy12** [comment]
Yeah, that's exactly what I used for my dynamic UI. Thanks for your help!
