### ISSUE TITLE
Shiny login button slow to load

### ISSUE THREAD

**Issue by explodecomputer** [MarkEdmondson1234/googleAuthR#51]
In the shiny example the login button takes longer to appear than the rest of the web page. Why is this and can it be avoided?

**Comment by MarkEdmondson1234** [comment]
Its because it builds the login URL before rendering, that depends on the app URL.  You can hardcode that in, for example the GentellaShiny button does that:
http://code.markedmondson.me/gentelellaShiny/login

**Comment by explodecomputer** [comment]
thanks for the quick reply
