### ISSUE TITLE
gar_auth_service / Issue for json_file: "The filename, directory name, or volume label syntax is incorrect"

### ISSUE THREAD

**Issue by kutasok** [MarkEdmondson1234/googleAuthR#54]
Plese, help with an issue described here http://stackoverflow.com/questions/41279504/r-the-filename-directory-name-or-volume-label-syntax-is-incorrect

I can't find solution for a whole day.

**Comment by kutasok** [comment]
Maybe you check somewhere the file name?

**Comment by MarkEdmondson1234** [comment]
Sounds weird, perhaps its an underlying directory.  You could also pass in the complete absolute file path (`c:\\mydir/blah/myjson.json`) instead.  Also do a `sessionInfo()` to check your version of R and packages and put it here - perhaps `httr` or `jsonlite` should be updated.

**Comment by MarkEdmondson1234** [comment]
It looks like a bug for Windows: https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16369

Are you 100% you have the right capitalisation?  I think if you pass the entire file-name for your JSON file you should avoid the need for normalising the path and it will work.

**Comment by kutasok** [comment]
Thank you!

**Comment by MarkEdmondson1234** [comment]
@kutasok glad it worked out
