### ISSUE TITLE
for quota exceeded errors, back off and try again

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAuthR#6]
If an API is queried to quickly, it will error.  Detect these errors and try the request again a few times.

**Comment by jdeboer** [comment]
Hi @MarkEdmondson1234 
If it is of any assistance to you, there is logic in the ganalytics package which is also designed to address this. You may want to adapt this code for use in the googleAuthR package.
https://github.com/jdeboer/ganalytics/blob/master/R/GaApiRequest.R#L171

**Comment by MarkEdmondson1234** [comment]
Thanks @jdeboer , I put your implementation in latest dev version 9001
