### ISSUE TITLE
gmail api

### ISSUE THREAD

**Issue by YerachmielWeiss** [MarkEdmondson1234/googleAuthR#63]
Add gmailr to the list of cross-compatible libraries!

**Comment by MarkEdmondson1234** [comment]
Well yes that would be nice, but there is a well established Gmail R client done form before this library was around - https://github.com/jimhester/gmailr

I am wanting to make it easier to work with other httr libraries though.

**Comment by YerachmielWeiss** [comment]
Okay.  Makes sense.  You did a great job!
