### ISSUE TITLE
Error in tokens[[token$hash()]] <- token :    cannot add bindings to a locked environment

### ISSUE THREAD

**Issue by smmurphy** [MarkEdmondson1234/googleAuthR#66]
I resolved this issue, but have noted here in case it informs future development...

The problem was mainly that I had set my expectations of behavior based on `gs_auth` in the `googlesheets` package which has a `cache` parameter in the function.  I think such a parameter would be a helpful addition to `gar_auth`.

## The Issue 
When trying to use gar_auth inside a function to handle connections to Google Analytics using a token stored in an .rds file using:

```
myFunction(){
...
gar_auth(token = GA_AUTH_FILE)
...
}
```
The connection ultimately worked, but I was getting the error:

```
Auto-refreshing stale OAuth token.
Error in tokens[[token$hash()]] <- token : 
  cannot add bindings to a locked environment
Request Status Code: 500
Error : is.response(x) is not TRUE
In addition: Warning message:
In retryRequest(do.call(request_type, args = arg_list, envir = asNamespace("httr"))) :
  Request failed before finding status code. Retrying.
Trying again: 1 of 5
Trying again: 2 of 5
Trying again: 3 of 5
Trying again: 4 of 5
Trying again: 5 of 5
All attempts failed.
```
The error is due to the cache for `httr` being updated from inside the function call.  I resolved this by setting `options(googleAuthR.httr_oauth_cache = FALSE)` before generating the token to store in the .rds file.  In retrospect this is pretty straightforward, but took some digging for me to resolve.  I had previously written a similar function for googlesheets and didn't run into this.  I think a `cache` parameter as exists for `gs_auth` would be a helpful addition to `gar_auth`.

**Comment by MarkEdmondson1234** [comment]
May I check your version, as I just did some work on this in the latest 0.5.0.  It should set `options(googleAuthR.httr_oauth_cache = "name_of_file")` if the argument `token` is a file path name as you show. 

It could also be that if you authenticated with an older version of a cache file, updated, and then loaded the new.  Could this be the case?

**Comment by smmurphy** [comment]
Thanks for checking this out! And for your suite of packages.  I am liking them a lot!

I am using googleAuthR_0.5.1, I saved the token today like so:

options(googleAuthR.httr_oauth_cache = FALSE)
saveRDS(token, file = "C:\\Path\\TokenOAuth.rds")

I just tried it again and I am back to the earlier error.  I think it worked last time because I had just regenerated the token.  The error seems to be triggered when the token is refreshed.

It still makes the connection, httr just throws that error.  I think this discussion on httr is relevant.

https://github.com/hadley/httr/issues/113

**Comment by MarkEdmondson1234** [comment]
Ah ok, maybe thats the issue then - I would do your function like this:

```
## save the token to custom .httr-oauth file
options(googleAuthR.httr_oauth_cache = "C:\Path\TokenOAuth.rds")
gar_auth()

## read the token again
gar_auth("C:\Path\TokenOAuth.rds")
```

That will then save the token to your filepath `"C:\Path\TokenOAuth.rds"` 
If you call the token directly via save/loadRDS you actually return a list of tokens, and this was mega confusing errors so I've tried to make it fail faster, but I can see its still non-obvious.  Now googleAuthR only will look at the first token, and rely on you calling the cache different names. 

Some more documentation with examples will help (if you agree that the above explains your issue?)

**Comment by MarkEdmondson1234** [comment]
And to help use `options(googleAuthR.verbose = 2)` and the new `gar_token_info()` command to keep an eye on what caches are being used and expected.

**Comment by smmurphy** [comment]
Thanks so much! Yes, this appears to work well.  I checked with both the initial load and with a refresh of the token, which is when the error was getting triggered previously, and everything appears to be working.
