### ISSUE TITLE
Allow renamed httr-oauth file (multiple account authentication change from hidden file)

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAuthR#7]
Some check that refreshes token from the appropriate token file.

**Comment by jdeboer** [comment]
Hi @MarkEdmondson1234 , just an idea I wanted to share for this, which I have been using in the ganalytics package, is to name the token file based on the supplied username, i.e. the email address that is used as a hint for authentication. You can see this happening here: https://github.com/jdeboer/ganalytics/blob/master/R/GaApiRequest.R#L46

**Comment by MarkEdmondson1234** [comment]
Great, thanks!  And I think its an option in httr too to name the file.  
I was wondering if its possible to store the credentials in say a MySQL database somewhere, say if you needed to refresh an account offline. I guess so.

**Comment by MarkEdmondson1234** [comment]
This also is a work around if for some reason you can't upload a hidden file to a server.

**Comment by MarkEdmondson1234** [comment]
This is covered by sending a file location name to `option(googleAuthR.httr_oauth_cache = "./new_name.token")`

**Comment by kutasok** [comment]
@jdeboer @MarkEdmondson1234 do you have examples of working with few token files?

**Comment by MarkEdmondson1234** [comment]
This is an example I use for switching between two different Google accounts with different Search Console and Google Analytics.  But in most cases, you will want to try and connect the sources with one email so you don't need to play with token caches a lot.


This generates the token into their own files e.g. not the default `.httr-oauth`
```r

## generating a new token for each service
    ## do google analytics auth
    options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/analytics",
                                            "https://www.googleapis.com/auth/analytics.readonly"),
            googleAuthR.httr_oauth_cache = "location-of-ga-token")
    ga_token <- googleAuthR::gar_auth(new_user = TRUE)

    ## do search console auth
    options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/webmasters",
            googleAuthR.httr_oauth_cache = "location-of-sc-token")
    sc_token <- googleAuthR::gar_auth(new_user = TRUE)

```

This uses them - make sure you have the same options of scopes and cache set as when you authenticated that token:

```r
## auth Google Analytics

## the [[1]] is to ensure you have the token, and not a list of tokens
  auth_token <- readRDS("location-of-ga-token")[[1]]
  options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/analytics", 
                                          "https://www.googleapis.com/auth/analytics.readonly"))
  googleAuthR::gar_auth(auth_token)

...run google analytics functions...


## auth Search Console
  
  auth_token <- readRDS("location-of-sc-token")[[1]]
  searchConsoleR::scr_auth(auth_token)

..run search console functions...
```

**Comment by kutasok** [comment]
Thank you a lot! Works well.
