### ISSUE TITLE
Client ID and Secret defaults to package supplied credentials when running deployed shiny apps

### ISSUE THREAD

**Issue by emadretina** [MarkEdmondson1234/googleAuthR#74]
Not sure if anyone else has seen this problem but when I tried deploying a shiny app it seems like it automatically defaults to the options provided by library rather than using mine. Has anyone else seen this issue?

**Comment by MarkEdmondson1234** [comment]
Hi @emadretina - yes unfortunetly this has come up before here https://github.com/MarkEdmondson1234/googleAuthR/issues/57 and https://github.com/MarkEdmondson1234/googleAuthR/issues/59

The fix at the moment is to either use the JS based auth, or to rebuild the package (e.g. clone github, rebuild) locally with your own details, as some kind of caching is taking place on Shinyapps.  I'll have another look at this to see if a better fix is available.

**Comment by emadretina** [comment]
Thank you, built it locally. Great work by the way, this is an amazingly useful package.

**Comment by MarkEdmondson1234** [comment]
@emadretina may I just check with you, if you were using the CRAN or the GitHub version as it is today?  The most recent version has no options specified.

**Comment by emadretina** [comment]
It was GitHub version. Also, I would suggest not putting the app id and secret in the code. I modified it to pull those from Env variables for local build.

**Comment by MarkEdmondson1234** [comment]
True, those client id/secret are throw away details but how you did it is the recommended way.  

I'm inquiring with [Shinyapps on this thread](https://groups.google.com/forum/#!topic/shinyapps-users/hWpR_Buclzw) to see if I can do anything. 

The very latest `googleAuthR`GitHub version has the client id/secret stripped away to force users to provide their own now, was that the version you used when deploying to Shinyapps or did it default back to the ones supplied? e.g. these ones:

```r
# googleAuthR.webapp.client_id = "201908948134-cjjs89cffh3k429vi7943ftpk3jg36ed.apps.googleusercontent.com",
# googleAuthR.webapp.client_secret = "mE7rHl0-iNtzyI1MQia-mg1o",
```

**Comment by MarkEdmondson1234** [comment]
Figured thats actually the best way to handle it, let you set your environment arguments which you can do by uploading an `.Renviron` file with your Shinyapp - the environment arguments are as below:

```r
* Default demo project scopes now NULL, set your own Google Project via `options(googleAuthR.scopes.selected)` or by setting up environment arguments:
   - `googleAuthR.client_id = Sys.getenv("GAR_CLIENTID")`
   - `googleAuthR.client_secret = Sys.getenv("GAR_CLIENT_SECRET")`
   - `googleAuthR.webapp.client_id = Sys.getenv("GAR_WEB_CLIENTID")`
   - `googleAuthR.webapp.client_secret = Sys.getenv("GAR_WEB_CLIENT_SECRET")`
   - `googleAuthR.scopes.selected = Sys.getenv("GAR_SCOPES")`
```

**Comment by lcolladotor** [comment]
Hm.... I'm not sure that's the syntax for `.Renviron`. Could you post an example? Is it something like:

```
GAR_CLIENTID="my id"
```

or more like:

```
googleAuthR.client_id = "My id"
```

I'm guessing it's the first option. In any case, it's good to know that this issue has been solved ^^.

**Comment by MarkEdmondson1234** [comment]
Its the former, but you have to restart your R session to see it.  Here are examples I have in my `Home` directory as seen by RStudio

```
#.Renviron
GAR_CLIENTID="kjsjfkjsfsf"
GAR_CLIENT_SECRET="sasdsad"
```

After restarting R they are reachable via:

```r
Sys.getenv("GAR_CLIENTID")
Sys.getenv("GAR_CLIENT_SECRET")
```

**Comment by lcolladotor** [comment]
Excellent, thanks!

**Comment by MarkEdmondson1234** [comment]
Hmm, you can't pass vectors if you want to do multiple scopes, so I'll set that up that you need a comma delimiter:

```
#.Renviron
GAR_CLIENTID="kjsjfkjsfsf"
GAR_CLIENT_SECRET="sasdsad"
GAR_SCOPES="scope1,scope2,scope3"
```

**Comment by MarkEdmondson1234** [comment]
I just need a confirmation this clears up the issue, no rebuilding needed.  I'll run a test myself next week-ish
