### ISSUE TITLE
Logging in loses previous data in Shiny

### ISSUE THREAD

**Issue by DavidRGriswold** [MarkEdmondson1234/googleAuthR#75]
This may not actually be an issue - it may simply be the nature of the beast - in which case I'd love some help figuring out how to deal with it.

I'm working on a Shiny app that basically allows for generating AP Statistics practice problems that can be exported, after generation, into various file types. It exports into Word, PDF, and now, thanks to this program, Google Docs. Unfortunately, if they first generate a problem they like THEN decide they want to export to Google Docs, the login process essentially deletes their work, since it redirects them back and the app "starts over".

Is this normal, an issue with googleAuthR, or something I am doing wrong? If it's normal, is there any way to potentially get around this? I don't want to force them to log in at the beginning since a lot of users will never need to log in at all. 

You can see the app (temporarily) at http://shiny.mtbos.org/testing/probgen .

**Comment by MarkEdmondson1234** [comment]
Right, I've assumed people only log in at the beginning!  But perhaps you can get around this by using the JavaScript based auth, that won't force a reload of Shiny.

**Comment by MarkEdmondson1234** [comment]
An example of how that works is here https://mark.shinyapps.io/googleAuthRMarkdown/

**Comment by DavidRGriswold** [comment]
Thank you! I'll play with that some.
