### ISSUE TITLE
Error when passing string with whitespace as a pars_args.

### ISSUE THREAD

**Issue by kmkmjohnson** [MarkEdmondson1234/googleAuthR#82]
Hi,
I'm using googleAuthR to update fields for chromeOS devices. The API takes several pars_args as strings. When I pass a string with no spaces, works great. When I pass a string that contains a space, I get the error below. Is there something I need to do to prep the string to be parsed correctly when it contains a whitespace?

```
Request Status Code: 400
Error : lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^
```

**Comment by MarkEdmondson1234** [comment]
Hmm it should catch this and do this, but it sounds as if the parameter is not being encoded.  To do it yourself, pass the parameter with spaces through `utils::URLencode(params, resevered = TRUE)`

e.g.

```r
utils::URLencode("myargs=hi mum&how=you doing")
# [1] "myargs=hi%20mum&how=you%20doing"
```

**Comment by kmkmjohnson** [comment]
Thanks. I gave that a try and didn't get an error (there were no spaces) but it kept the encoding in the final value in the field when viewed via google admin.

So "testing testing" = error.
"testing_testing" = no error and end result is "testing_testing"
"testing%20testing" = no error but space still encoded in the end when viewed in google admin (end result is "testing%20testing")

**Comment by MarkEdmondson1234** [comment]
I'm not familiar with this API, is this your reference? https://developers.google.com/admin-sdk/directory/v1/reference/chromeosdevices/patch

Perhaps you are using `GET` instead of `PATCH`?  Could you share a bit of code?

**Comment by kmkmjohnson** [comment]
I'm actually doing `update`. https://developers.google.com/admin-sdk/directory/v1/reference/chromeosdevices/update

Here is my function that does the update:
```
update_Chrome_device <-
  function(my_customerId,
           my_deviceId,
           my_annotatedAssetId,
           my_annotatedLocation,
           my_annotatedUser,
           my_notes,
           my_orgUnitPath) {
    
    options("googleAuthR.rawResponse" = TRUE)
    
    f <-
      gar_api_generator(
        "https://www.googleapis.com/admin/directory/v1",
        "PUT",
        path_args = list(
          customer = my_customerId,
          devices = paste("chromeos", my_deviceId, sep = "/")
        ),
        pars_args = list(
          annotatedAssetId = my_annotatedAssetId,
          annotatedLocation = my_annotatedLocation,
          annotatedUser = my_annotatedUser,
          notes = my_notes,
          orgUnitPath = my_orgUnitPath
        )
      )
    
    body <- list(
      annotatedAssetId = my_annotatedAssetId,
      annotatedLocation = my_annotatedLocation,
      annotatedUser = my_annotatedUser,
      notes = my_notes,
      orgUnitPath = my_orgUnitPath
    )
    
    f(the_body = body)
    
    options("googleAuthR.rawResponse" = FALSE)
  }
```

**Comment by MarkEdmondson1234** [comment]
You are passing both in the body and via `pars_args` - I think you should only need one of those.  Favour the body arguments, so perhaps:

```r
    f <-
      gar_api_generator(
        "https://www.googleapis.com/admin/directory/v1",
        "PUT",
        path_args = list(
          customer = my_customerId,
          devices = paste("chromeos", my_deviceId, sep = "/")
        )
      )
    
    body <- list(
      annotatedAssetId = my_annotatedAssetId,
      annotatedLocation = my_annotatedLocation,
      annotatedUser = my_annotatedUser,
      notes = my_notes,
      orgUnitPath = my_orgUnitPath
    )
    
    f(the_body = body)
```

Is the problem field `my_notes` ?

Could we also just eliminate its an API issue?  If you copy over your R test arguments to the API tester on the doc page, does the problem go away? https://developers.google.com/admin-sdk/directory/v1/reference/chromeosdevices/patch

 A screenshot of the response sent/received from that tool will also be helpful.  I haven't access to test myself, unfortunately.

**Comment by MarkEdmondson1234** [comment]
@kmkmjohnson did this get sorted?

**Comment by kmkmjohnson** [comment]
I'm sorry. I haven't had a chance to work on it. Will do that by tomorrow and let you know.

**Comment by MarkEdmondson1234** [comment]
No rush, just checking :)

**Comment by MarkEdmondson1234** [comment]
This should be fixed now in https://github.com/MarkEdmondson1234/googleAuthR/issues/101
