### ISSUE TITLE
Google Sheets request URL has a double slash causing a 404 error

### ISSUE THREAD

**Issue by jphillips-modexe** [MarkEdmondson1234/googleAuthR#91]
I have the following code which is trying to read from a Google Sheet (the REST call is documented here: [https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get))

However when I make the call I get a 404 error back: `The requested URL <code>/v4/spreadsheets//XXXXXXXXX?ranges=Employees%21A1%3A1</code> was not found on this server`

I believe its the double forward slash after the path component `spreadsheets` that is causing the problem.

The code I am running is as follows (I have masked out the real s/sheet Id for security).

```
options("googleAuthR.scopes.selected" = c("https://www.googleapis.com/auth/spreadsheets.readonly"))
options(googleAuthR.rawResponse = TRUE)

gar_auth_service(json_file="~/gsheets-credentials.json")

gsheets_get_func = gar_api_generator(baseURI = "https://sheets.googleapis.com/v4/spreadsheets",
                                     http_header = "GET",
                                     path_args = list("XXXXXXXXX"),
                                     pars_args = list(ranges = "Sheet1!A1:1"),
                                     data_parse_function = function(x) print(rawToChar(x)) )

gsheets_get_func()
```

Happy to accept this is user error, but any ideas or fixes would be very welcome, thanks.

**Comment by MarkEdmondson1234** [comment]
There is a `checkTrailingSlash=TRUE`option that was raised by this issue https://github.com/MarkEdmondson1234/googleAuthR/issues/73 - perhaps that helps?

Also just making sure you know about the `googlesheets`library which may already do what you are attempting.

**Comment by MarkEdmondson1234** [comment]
Also set this: `option(googleAuthR.verbose = 2)` and you'll get more info to debug, and can post its output here.

**Comment by jphillips-modexe** [comment]
Hi, thanks for the prompt response. That suggestion has got me past the issue but I have encountered another.

Not wishing to pollute this ticket with lots of other things, but the error I am getting is `Error in file.exists(httr_cache) : invalid 'file' argument`.

The verbosity setting does not give any more output than that. If there is a ticket with a solution with a fix then happy to close this one down and refer to that.

**Comment by MarkEdmondson1234** [comment]
I am literally just working on this now so may be in flux, but you could try the current GitHub version which should give a lot more info or solve the issue.  Its in development now though so may be a couple of days until stable.

**Comment by jphillips-modexe** [comment]
OK. I did install the GH version using the command `devtools::install_github("MarkEdmondson1234/googleAuthR")`.

**Comment by jphillips-modexe** [comment]
Sorry I should have also said I got the message `Token exists.` as well.

**Comment by MarkEdmondson1234** [comment]
If you are not using JSON to auth, I guess it will be sorted if you delete your `.httr-oauth` file and reauth. Also make sure to restart the R session.

**Comment by jphillips-modexe** [comment]
That worked, many thanks.
