### ISSUE TITLE
Remove 'approval_prompt':'force' option in gar_auth_jsUI

### ISSUE THREAD

**Issue by jon-harmon-macmillan** [MarkEdmondson1234/googleAuthR#93]
shiny.R
Lines 37-38:
```
,
          'approval_prompt':'force'
```

If that were gone, the JS version of the authentication (which doesn't reload the page) would work in Shiny and not require the user to re-approve every time they visit the page. Alternatively, pass it in as a parameter.

**Comment by MarkEdmondson1234** [comment]
Yes, its on this issue but I haven't had a crack at it yet https://github.com/MarkEdmondson1234/googleAuthR/issues/60

**Comment by MarkEdmondson1234** [comment]
@jonthegeek ok this is in now, give it a go.
