### ISSUE TITLE
Example shinyapps app: Error in with_shiny: Need to provide the reactive access token in shiny_access_token argument. e.g. shiny_access_token=access_token()

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAuthR#98]
For some users, see this error when using https://mark.shinyapps.io/googleAuthRexample/

But I don't see  the same when I try.  Hmm.

**Comment by alptaciroglu** [comment]
I started to have this error after trying to get my second shiny app Google Authenticated Login. Is there any updates on the issue?

**Comment by MarkEdmondson1234** [comment]
I need a reproduceable example to start, would you have your code that replicates it?

**Comment by alptaciroglu** [comment]
Thank you for quick reply.. Let me know if all of the code is needed. Was working quite alright with only one app authenticated via Google. Don't know if that's related

##global.R

`## options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/plus.me"))
## rmarkdown::run("googleAuthRMarkdown.Rmd")

## gar_auth()

## setGoogleAuthOptionsOdyssey <- function(){

options(shiny.maxRequestSize=30*1024^2)  
options(shiny.port = 1222)
options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/userinfo.email",
                                        "https://www.googleapis.com/auth/userinfo.profile"))

options(googleAuthR.webapp.client_id = "CLIENT ID")
options(googleAuthR.webapp.client_secret = "CLIENT SECRET")

## }
`
#####################################################################

##server.R

`source('global.R')
## setGoogleAuthOptionsOdyssey()

shinyServer(function(input, output, session) {
  
  source('functionsArsenal.R', local=TRUE)
  
  network.data <- reactiveValues(CytoscapeFile = NULL, index = NULL, login = FALSE)

  biomartGSEmRNA <- reactive({   # Read all three annotation files for converting probe ids in the expression data to gene names
    switch(input$Platform,
           "GPL570" = read.table("biomartGSEmRNA_GPL570.csv", sep=",", header=T, check.names=F),
           "GPL96" = read.table("biomartGSEmRNA_GPL96.csv", sep=",", header=T, check.names=F),
           'GPL97'= read.table("biomartGSEmRNA_GPL97.csv", sep=",", header=T, check.names=F))
  }) 

 shinyjs::disable('SideButton')
 hideTab(inputId = "sidetabs", target = "SideExprs1")
 hideTab(inputId = "sidetabs", target = 'NetworkOptions')
 hideTab(inputId = "tabs", target = 'panelExprs')
 hideTab(inputId = "tabs", target = 'panelCyto')
 hideTab(inputId = "tabs", target = 'panelNetwork')
  
  
  access_token_odyssey <- callModule(googleAuth, "OdysseyAuth", approval_prompt = 'auto')
  ## to use in a shiny app:
  user_details_odyssey <- reactive({
    validate(
      need(access_token_odyssey(), "Authentication Required!")
    )
    user <- with_shiny(get_user_info, shiny_access_token = access_token_odyssey())
    if(whitelist(user, c('alptaciroglu@gmail.com'))) {
      network.data$login <- TRUE
      shinyjs::enable('SideButton')
      showTab(inputId = "sidetabs", target = "SideExprs1")
      showTab(inputId = "sidetabs", target = 'NetworkOptions')
      return(user)
    } else {
      validate(
        need(network.data$login == TRUE, 'Your email is not part of the authorized emails for Odyssey ')
      )
      stop()
    }
  })
  
  output$user_name <- renderText ({
    user_details_odyssey()
    if(network.data$login == FALSE){
      'Not yet Authenticated !'
    }
    else{
      user_details_odyssey()$displayName
    }
  })  

### .... rest of the server.R - doubt but not sure if needed
`

#################################################################

## UI.R

`
                  tabPanel("Authentication", value="AuthenticationPanel",
                           wellPanel(
                             fluidRow(
                               column(8,
                                      googleAuthUI("OdysseyAuth")))),
                           wellPanel(
                             fluidRow(
                               column(8,
                                      list(HTML('<p style="font-family:Chicle; color:#464646; font-size:16px; font-weight:500"> Logged in as: </p>'), h3(textOutput("user_name"))))),
                             tags$head(tags$style("#user_name{color: #464646;
                                 font-size: 20px;
                                 font-style: italic;
                                 font-family: Chicle;
                                 text-decoration: underline;
                                 }"
                                 )
                                 ),
                             fluidRow(
                               column(8,
                                      HTML('<p style="font-family:courier; color:#B54B4B"> If login fails, please contact the administrator </p>')
                                      )
                             )
                           )),

## rest of UI.R - doubt but not sure if rest is needed
 `

**Comment by MarkEdmondson1234** [comment]
I guess `user_details_odyssey()` is returning `NULL` due to not authenticating successfully, which is where the real error is (would be cool to confirm this with a `browser()` in the right place within your Shiny app.

If the `options(googleAuthR.verbose = 1)` setting is also set it will return more debugging info.

Does this only occur on shinyapps.io or locally?  IF on Shinyapps it may be related to this issue ( https://github.com/MarkEdmondson1234/googleAuthR/issues/74 ) where Shinyapps overwrites option settings, setting via environment arguments instead fixes that issue. 

I would also be careful hiding elements via JS if that involves the auth button - the way Shiny works it could mean the auth code doesn't get executed - could that be the case?

**Comment by alptaciroglu** [comment]
Thanks for the reply. 

This happened in both shinyapps.io and local but I have some questions.

I had created two different projects under Google APIs to have an organized view of my apps. Each had a web application located within with their service accounts. I wonder if getting it reduced to one project makes it unsafe or cannot properly be deployed to shinyapps. 

I haven't had users for now, as the apps are under development so I do not know the aftermath. Also would they need two different service accounts? 

What I did was to kill port processes on 1221 where I run shiny and restart everything from scratch and then it worked for the app I developed (nearly) prior.

**Comment by MarkEdmondson1234** [comment]
Ok if I happens locally then I think its most likely due to failed authentication due to lost scopes, permission or something - scan through the [help section](http://code.markedmondson.me/googleAuthR/articles/troubleshooting.html) to check all is well there.

Its fine either way to have only one or two Google project for two APIs, the projects are mostly for billing and authentication ease, if I can I put them under one since then its the same service account and easier to deal with. If you do need services from another project (say a client) then you can add the first project's service account email as a user to the other project, to get similar access. 

It sounds as if it may be related if the URL authentication call back URL is not the same port or service email for both Shiny apps - you can add multiple call back URLs in one project but if not set perhaps effects deployment.  You may also want to try using JS based auth since thats an alternative way to set it up and you need to be more explicit in the URL you are deploying from.

**Comment by MarkEdmondson1234** [comment]
No changes I think would affect this, you can always check versions via `sessionInfo()`- if it ends with `.9000` then its an unstable dev GitHub version.

I would suggest putting in a `browser()` command for just before you call the `with_shiny()` then inspect the token which should be of class `Token2.0` - if not then something has failed, I guess the clientid/secret perhaps?  You can check those with `getOptions("googleAuthR.webapp.client_id")`

**Comment by alptaciroglu** [comment]
I really do not know .. I have tried putting up a browser() command and the token return had failed before then. It was the same secret and clientid, my supervisor and me checked triple times before we quit trying. Glad it's working now though :+1:

**Comment by MarkEdmondson1234** [comment]
Well glad its working, perhaps the auth was clashing with auto-auth in your `.Renviron` which are not present now?  (Such as `GA_AUTH_FILE`).  Well I'll closo this but if it comes up again do let me know.
